### ISSUE TITLE
name 'libply_c' is not definded 

### ISSUE THREAD

**Issue by deepdata-foundation** [loicland/superpoint_graph#1]
After make smooth, use python partition_Semantic3D.py --SEMA3D $SEMAN3D_DIR

Get this error

=================
   test_reduced/
=================
1 / 14---> sg28_station2
    creating the feature file...
Traceback (most recent call last):
  File "partition_Semantic3D.py", line 92, in <module>
    xyz, rgb = prune(data_file, args.ver_batch, args.voxel_width)
  File "/mnt/diskb/dixinhan/Deep_3D/Pointnet/superpoint_graph/partition/provider.py", line 357, in prune
    xyz_sub, rgb_sub, l = libply_c.prune(xyz_full, voxel_width
NameError: name 'libply_c' is not defined

**Comment by loicland** [comment]
Hi!

Indeed, there was a relative path issue in provider added by a recent commit. I reverted it, let me know if it fixes it for you.

**Comment by deepdata-foundation** [comment]
Run Smooth

Thank you!!!
