### ISSUE TITLE
ImportError: No module named 'libcp'

### ISSUE THREAD

**Issue by post2web** [loicland/superpoint_graph#10]
I get the import error when I try to run:
```
python partition/write_Semantic3d.py --SEMA3D_PATH $SEMA3D_DIR --odir "results/sema3d/best" --db_test_name testred
Traceback (most recent call last):
  File "partition/write_Semantic3d.py", line 20, in <module>
    import libcp
ImportError: No module named 'libcp'
```

**Comment by post2web** [comment]
Fixed it by adding this:
```
sys.path.append("./partition/cut-pursuit/src")
sys.path.append("./partition/ply_c")
```
to write_Semantic3d.py

**Comment by loicland** [comment]
Right, good catch, changing it now.

**Comment by WanpengShao** [comment]
Hi:

I have this in partition:
sys.path.append("/media/wpshao/D_Disk/ubuntu_code/partition/cut-pursuit/build/src")
sys.path.append("/media/wpshao/D_Disk/ubuntu_code/partition/ply_c")
sys.path.append("/media/wpshao/D_Disk/ubuntu_code/partition")
And I have compliled the libply_c and libcp and get libply_c.so and libcp.so.
But still:
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'libcp'
How to fixed it?
