### ISSUE TITLE
building on Debian Buster

### ISSUE THREAD

**Issue by josch** [loicland/superpoint_graph#101]
Hi,

the instructions written in the README.md are a bit long-winded. In case it helps, here are some simpler instructions that helped me on Debian Buster, starting from a fresh install:

Installing proprietary nvidia stuff from non-free repositories:

    sudo apt install nvidia-driver nvidia-cuda-toolkit

Installing development libraries:

    sudo apt install git cmake build-essential libboost-dev libboost-python-dev libboost-numpy-dev libboost-graph-dev libeigen3-dev

Installing Python libraries

    sudo apt install python3-sklearn python3-igraph python3-h5py python3-numpy python3-pip

Installing everything from pypi that is not shipped by Debian:

    pip3 install plyfile torch torchnet transforms3d cupy pynvrtc

Then clone the project:

    git clone https://github.com/loicland/superpoint_graph.git
    cd superpoint_graph/
    git clone https://github.com/loicland/cut-pursuit.git

Build it:

```
mkdir partition/ply_c/build
cmake -Hpartition/ply_c -Bpartition/ply_c/build
cmake --build partition/ply_c/build

mkdir cut-pursuit/src/build
cmake -Hcut-pursuit/src -Bcut-pursuit/src/build
cmake --build cut-pursuit/src/build
```

Make sure that applications know about the libraries we built:

    export PYTHONPATH=/home/user/superpoint_graph/cut-pursuit/src/build/:/home/user/superpoint_graph/partition/ply_c/build

The commands that can then be run are just like in the original `README.md`. Maybe this helps somebody.

**Comment by loicland** [comment]
Thanks! I am sure that would be useful.
