### ISSUE TITLE
how to display spg with cloudcompare?

### ISSUE THREAD

**Issue by YijunTang** [loicland/superpoint_graph#104]
Hi, loic,

Thanks for your great job. you recommend using CloudCompare to display intermediary step result in [issue#62](https://github.com/loicland/superpoint_graph/issues/62#issuecomment-438947277), and how to do it?

**Comment by loicland** [comment]
Hi. Use the `partition/visualize` function to create some .ply (located in `clouds`), and pretty much drag and drop them on meshlab/cloudCompare.
