### ISSUE TITLE
How to get the labels for the original points using the trained model?

### ISSUE THREAD

**Issue by therealanshuman** [loicland/superpoint_graph#109]
Assuming I have the trained `model.pth.tar` file on a custom dataset, how can I get the labels for the original point cloud? Correct me if I'm wrong, the model outputs labels for the superpoint graph.

**Comment by loicland** [comment]
You can use the function visualize with `output_type r`, or adapt the function `partition/write_Semantic3d`.
If you want to have the results on the original, non subsampled point cloud, add the option `--up sample 1`
