### ISSUE TITLE
How to judge whether  the superpoint partitioning is reasonable？

### ISSUE THREAD

**Issue by justbin1123** [loicland/superpoint_graph#110]
re

**Comment by loicland** [comment]
Hi,

if you want a quantitative evaluation of how good your partition is, you can compute the oracle prediction which associate to each superpoint its majority label. This will give you an upper bound of how good the superpoint classification can actually be.

It should be straightforward using the sp_labels field in the spg .h5 files. let me know if it is unclear for you how to do it.
