### ISSUE TITLE
code bug

### ISSUE THREAD

**Issue by truebelief** [loicland/superpoint_graph#127]
This is a amazing work and I've made it through for my own ascii dataset. There needs a bit tuning work, but the results look good so far. I just found two confusing parts from your code.

1. the argument **d_max** has no use,
in the file **partition.py**
`parser.add_argument('--d_se_max', default=0, type=float, help='max length of super edges')`
It seems the argument **d_max** can remove some unnecessary graph edges. But looking at the function in **graphs.py**:
`def compute_sp_graph(xyz, d_max, in_component, components, labels, n_labels):`
The d_max is not used anywhere in this function.
I think trimming graph edges with d_max is important, especially for some complex point clouds dataset, so please make this d_max work again.

2. a possible error
still in the function in **graphs.py**: `def compute_sp_graph(xyz, d_max, in_component, components, labels, n_labels):`
there is a line `if len(delta > 1):` to compute standard deviation in a rapid way
but it seems a correct one should be `if len(delta) > 1:`

**Comment by loicland** [comment]
You are absolutely correct. Fixed both of these issues in the latest commit.

thanks for your vigilance!
