### ISSUE TITLE
rgb array scrambled by libply_c.prune()

### ISSUE THREAD

**Issue by bimtauer** [loicland/superpoint_graph#130]
Thanks for your great work! 

I discovered an issue when trying to visualize pruned point clouds with their original colors:
The rgb array returned by prune is scrambled as visible in the screenshot.

![Screenshot_20190626_151711](https://user-images.githubusercontent.com/30375389/60182961-9d31a880-9825-11e9-85da-e13484ab0100.png)

I could reproduce this behavior with the following lines:

```
xyz = np.random.rand(100, 3) * 1000
rgb = np.random.rand(100, 3)
labels = np.random.rand(100, 1)

xyz_pr, rgb_pr, labels_pr = libply_c.prune(xyz, 0.03, rgb, labels, 1)


```

**Comment by loicland** [comment]
Hi,

what do you mean by scramble?

Eitherway, can you try:
```
xyz = np.ascontiguousarray(xyz, dtype='float32')
rgb = np.ascontiguousarray(rgb, dtype='uint8')
```

**Comment by bimtauer** [comment]
Hi there, thanks for the quick answer! 

Adding that line to the read_las function before pruning did the job!
