### ISSUE TITLE
Typo in PR #133

### ISSUE THREAD

**Issue by Pandinosaurus** [loicland/superpoint_graph#135]
Following merged PR #133, I noticed an awkward typo in first code section, making the git command point to my fork instead of the original repository. Could you please replace the following ?
```
git clone --recurse-submodules https://github.com/Pandinosaurus/superpoint_graph
```
with 
```
git clone --recurse-submodules https://github.com/loicland/superpoint_graph
```

**Comment by loicland** [comment]
changed! I will test everyhting extensively soon, I am working on integrating the supervized partition to the code now.
