### ISSUE TITLE
Bug in Readme

### ISSUE THREAD

**Issue by maximiliangoettgens** [loicland/superpoint_graph#14]
When executing:

> python partition/write_Semantic3D.py --SEMA3D_PATH $SEMA3D_DIR --odir "results/sema3d/best" --db_test_name testred

Error:
`python: can't open file 'partition/write_Semantic3D.py': [Errno 2] No such file or directory`

Bug: 'write_Semantic3D.py' should have a lowercase d
Best,
Max

**Comment by loicland** [comment]
thanks for catching that - fixed.
