### ISSUE TITLE
Why it's pred_full+1 instead of pred_full in the visulization

### ISSUE THREAD

**Issue by KangweiLiu** [loicland/superpoint_graph#144]
Hello，dear
Why it used pred_full+1 instead of just pred_full while visualizing the final result , such as in "prediction2ply(ply_file + "_pred.ply", xyz, pred_full+1, n_labels,  args.dataset)" ?

**Comment by loicland** [comment]
Hi,

0 is a reserved value in the ground truth for unannotated data, so the first class starts at 1. However, the network annotates all data and hence never predict 'unannotated'. consequently, the output starts at class 0, with a shift of 1 comapred to the ground truth.

I will add an addendum in the README, this questions comes back a lot!

**Comment by KangweiLiu** [comment]
I got it， thanks！

> Hi,
> 
> 0 is a reserved value in the ground truth for unannotated data, so the first class starts at 1. However, the network annotates all data and hence never predict 'unannotated'. consequently, the output starts at class 0, with a shift of 1 comapred to the ground truth.
> 
> I will add an addendum in the README, this questions comes back a lot!

I got it， thanks！
