### ISSUE TITLE
How to train npm3d dataset with this model?

### ISSUE THREAD

**Issue by Sajjadmanal** [loicland/superpoint_graph#149]
Hi,

Will your model also work for [NPM3D](http://npm3d.fr/paris-lille-3d) dataset too? If yes, how to proceed with it?

**Comment by loicland** [comment]
Sure! You will need to adapt a few things, mostly the reader function. Follow the instructions in `Other dataset` in the README. Let me know if you encounter issues.

**Comment by Sajjadmanal** [comment]
Ok. I will try. Does it works on Windows?

**Comment by loicland** [comment]
I never tried. I doubt it. Would be easier to use a VM in my opinion.

**Comment by Sajjadmanal** [comment]
Ok. I wil try that.

**Comment by zzusunquan** [comment]
> 好。我会尝试的。
I'm sorry to disturb you
What is your result on the NPM3D dataset，The result I made is not very good, how is your result ?
