### ISSUE TITLE
How to visualize the data on S3DIS? The README only provide the visualization process on Semantic3d and KITTI.

### ISSUE THREAD

**Issue by THHHomas** [loicland/superpoint_graph#150]

**Comment by loicland** [comment]
From the README:

To visualize the results and all intermediary steps, use the visualize function in partition (for S3DIS, vKITTI3D,a nd Semantic3D). For example:
```
python partition/visualize.py --dataset s3dis --ROOT_PATH $S3DIR_DIR --res_file results/s3dis/pretrained/cv1/predictions_test --file_path Area_1/conferenceRoom_1 --output_type igfpres
```
output_type defined as such:

'i' = input rgb point cloud
'g' = ground truth (if available), with the predefined class to color mapping
'f' = geometric feature with color code: red = linearity, green = planarity, blue = verticality
'p' = partition, with a random color for each superpoint
'r' = result cloud, with the predefined class to color mapping
'e' = error cloud, with green/red hue for correct/faulty prediction
's' = superedge structure of the superpoint (toggle wireframe on meshlab to view it)
Add option --upsample 1
