### ISSUE TITLE
Train accuracy and loss are fine but Test Loss and accuracy are unreasonable??

### ISSUE THREAD

**Issue by ShichaoJin** [loicland/superpoint_graph#154]
Step1:  I configure my environment using nvidia-docker by following README.md in your respository
Step2:  I run the Semantic3D examples by foloowing the Semantic3D.md 
## when I train on the whole publicly available data and test on the reduced test set, i.e., run the following code:
![image](https://user-images.githubusercontent.com/28957118/66387913-92c3a500-e9f7-11e9-82cc-fe0c7dc14681.png)

The results was shown bellow. The training accuracy and loss seem reasonable, which is increasing gradually, but the testing accuracy was quite small and the testing loss was much larger than the train loss. 

![image](https://user-images.githubusercontent.com/28957118/66387682-087b4100-e9f7-11e9-951e-f712f1af86c9.png)

Thx for you help in advance,

**Comment by loicland** [comment]
Hi,

this is because there is no ground truth on the test set of semantic3d.

**Comment by garryz94** [comment]
Hi @ShichaoJin , can you tell me how to compile libply_c and libcp in docker? Do i have to install anaconda in docker environment? I am kind of stuck here
