### ISSUE TITLE
visualization

### ISSUE THREAD

**Issue by longmalongma** [loicland/superpoint_graph#156]
hello,i only have one rtx2080gpu,can i run your semantic segmentation on your three types of dataset?

**Comment by loicland** [comment]
Hi. You'd probably be able.to run inference just fine. For training you might have to use smaller batches, and maybe change the norms to group norms.

Otherwise just use your CPU.

**Comment by longmalongma** [comment]
ok,think you for reply,i am trying to run your codes. when do you provide some codes about scannet data?




------------------ 原始邮件 ------------------
发件人: "Loic Landrieu"<notifications@github.com>;
发送时间: 2019年10月11日(星期五) 晚上8:55
收件人: "loicland/superpoint_graph"<superpoint_graph@noreply.github.com>;
抄送: "longma"<1442342449@qq.com>;"State change"<state_change@noreply.github.com>;
主题: Re: [loicland/superpoint_graph] visualization (#156)




Hi. You'd probably be able.tomrun inference just fine. For training you might have to use smaller batches, and maybe change the norms to group norms.
 
Otherwise just use your CPU.

**Comment by longmalongma** [comment]
hi,i want to know if my one gpu memory is insufficient to load the dataset,two gpus do it?i have no idea that two gpus if can increase the memory?


------------------ 原始邮件 ------------------
发件人: "Loic Landrieu"<notifications@github.com>;
发送时间: 2019年10月11日(星期五) 晚上8:55
收件人: "loicland/superpoint_graph"<superpoint_graph@noreply.github.com>;
抄送: "longma"<1442342449@qq.com>;"State change"<state_change@noreply.github.com>;
主题: Re: [loicland/superpoint_graph] visualization (#156)




Hi. You'd probably be able.tomrun inference just fine. For training you might have to use smaller batches, and maybe change the norms to group norms.
 
Otherwise just use your CPU.

**Comment by loicland** [comment]
Hi,

I think yo should probably try it! I haven't tested this network on a multi-GPU setting personally.

**Comment by longmalongma** [comment]
> Hi,
> 
> I think yo should probably try it! I haven't tested this network on a multi-GPU setting personally.
Thank your very much!
