### ISSUE TITLE
Nadaraya-Watson estimation

### ISSUE THREAD

**Issue by brotherNanNan** [loicland/superpoint_graph#16]
Hi, loicland：
        have you released the code about Nadaraya-Watson estimation for interpolating labels of full point cloud ? thks

**Comment by loicland** [comment]
Hi, in our experiments 1nn was as efficient as 10nn, so this is what is implemented (and reflected in the new version of the article that we will release in a couple days). To interpolate use ```/partition/write_s3dis.py``` or ```--upsample 1``` in ```/partition/visualize.py```.
