### ISSUE TITLE
IndexError: too many indices for array

### ISSUE THREAD

**Issue by zzusunquan** [loicland/superpoint_graph#169]
Hi  I am sorry to bother you.
while I run  python learning/sema3d_dataset.py --SEMA3D_PATH /home/s206/Documents/sunquan/superpoint_graph-ssp-spg/SEMA3D_DIR
Traceback (most recent call last):
  File "learning/sema3d_dataset.py", line 139, in <module>
    preprocess_pointclouds(args.SEMA3D_PATH)
  File "learning/sema3d_dataset.py", line 96, in preprocess_pointclouds
    for file in os.listdir(pathC):
FileNotFoundError: [Errno 2] No such file or directory: '/home/s206/Documents/sunquan/superpoint_graph-ssp-spg/SEMA3D_DIR/superpoint_graphs/train/'
Then  i change the sema3d_dataset.py  line 90  features_supervision to features 
 
 run  python learning/sema3d_dataset.py --SEMA3D_PATH 
/home/s206/Documents/sunquan/superpoint_graph-ssp-spg/SEMA3D_DIRdomfountain_station3.h5
Traceback (most recent call last):
  File "learning/sema3d_dataset.py", line 139, in <module>
    preprocess_pointclouds(args.SEMA3D_PATH)
  File "learning/sema3d_dataset.py", line 103, in preprocess_pointclouds
    hard_labels = np.argmax(labels[:,1:],1)
IndexError: too many indices for array

then I debug the sema3d_dataset.py  i found 

![image](https://user-images.githubusercontent.com/48703273/68211048-bdfadd80-0011-11ea-9334-9b28e5179071.png)
The labels array is empty and causes this error?
So I want to ask where to put the .labels file.
 SEMA3D_DIR/data? or SEMA3D_DIR?  or SEMA3D_DIR/data/train?
Or what other possible problems caused this error？

**Comment by loicland** [comment]
Hi,

"The label files of the training files must be put in the same directory than the .txt files.", so SEMA3D_DIR/data/train.

you must relaunch the partition step however.

**Comment by zzusunquan** [comment]
> Hi,
> 
> "The label files of the training files must be put in the same directory than the .txt files.", so SEMA3D_DIR/data/train.
> 
> you must relaunch the partition step however.

Thank you very much for your answer. I would like to ask if the labels file needs to decompressed. 
And I don’t know whether the label array is empty cause this problem .
When I use h5 explore to open the domfountain_station3.h5 there is nothing in the branch of labels.

**Comment by loicland** [comment]
You download the labels in plain text from the semantic3d website.

For the train set, features/features_supervision must have a field `labels` of size N by 9. in the test/test_reduced it is just a simple scalar : 0.

**Comment by zzusunquan** [comment]
Ok, thank you very much for your patience. Since I am late at night, I will go to the studio tomorrow and continue experiment. Thank you for giving me hope to continue. I wish you all the best

**Comment by longmalongma** [comment]
> You download the labels in plain text from the semantic3d website.
> 
> For the train set, features/features_supervision must have a field `labels` of size N by 9. in the test/test_reduced it is just a simple scalar : 0.



> You download the labels in plain text from the semantic3d website.
> 
> For the train set, features/features_supervision must have a field `labels` of size N by 9. in the test/test_reduced it is just a simple scalar : 0.

Hello,i meet this problem:
 IndexError: too many indices for array
how to ｏrganize "labes" files have download from website? Could you be more specific？looking forward your reply.

**Comment by longmalongma** [comment]
> > Hi,
> > "The label files of the training files must be put in the same directory than the .txt files.", so SEMA3D_DIR/data/train.
> > you must relaunch the partition step however.
> 
> Thank you very much for your answer. I would like to ask if the labels file needs to decompressed.
> And I don’t know whether the label array is empty cause this problem .
> When I use h5 explore to open the domfountain_station3.h5 there is nothing in the branch of labels.

Hello,have you solved this problem,where can download the labels in plain text from the semantic3d website?

**Comment by zzusunquan** [comment]
> > > 嗨，
> > > “训练文件的标签文件必须与.txt文件放在同一目录中。”，所以SEMA3D_DIR / data / train。
> > > 但是，您必须重新启动分区步骤。
> > 
> > 
> > 非常感谢您的回答。我想问一下标签文件是否需要解压缩。
> > 而且我不知道标签数组是否为空会导致此问题。
> > 当我使用h5浏览打开domfountain_station3.h5时，标签的分支中没有任何内容。
> 
> 您好，您已经解决了这个问题，在哪里可以从语义3d网站下载纯文本标签？
![image](https://user-images.githubusercontent.com/48703273/70401158-6b29a100-1a69-11ea-94cc-a6d613162d0b.png)
This is  semantic website
http://www.semantic3d.net/view_dbase.php?chl=2

**Comment by longmalongma** [comment]
> > > > 嗨，
> > > > “训练文件的标签文件必须与.txt文件放在同一目录中。”，所以SEMA3D_DIR / data / train。
> > > > 但是，您必须重新启动分区步骤。
> > > 
> > > 
> > > 非常感谢您的回答。我想问一下标签文件是否需要解压缩。
> > > 而且我不知道标签数组是否为空会导致此问题。
> > > 当我使用h5浏览打开domfountain_station3.h5时，标签的分支中没有任何内容。
> > 
> > 
> > 您好，您已经解决了这个问题，在哪里可以从语义3d网站下载纯文本标签？
> > ![image](https://user-images.githubusercontent.com/48703273/70401158-6b29a100-1a69-11ea-94cc-a6d613162d0b.png)
> > This is  semantic website
> > http://www.semantic3d.net/view_dbase.php?chl=2

Hi,thank you for your reply. I have downloaded it. Which folder should I put it in?

**Comment by zzusunquan** [comment]
> > > > > 嗨，
> > > > > “训练文件的标签文件必须与.txt文件放在同一目录中。”，所以SEMA3D_DIR /数据/火车。
> > > > > 但是，您必须重新启动分区步骤。
> > > > 
> > > > 
> > > > 非常感谢您的回答。我想问一下标签文件是否需要解压缩。
> > > > 而且我不知道标签上面是否为空会导致此问题。
> > > > 当我使用h5浏览打开domfountain_station3.h5时，标签的分支中没有任何内容。
> > > 
> > > 
> > > 您好，您已经解决了这个问题，在哪里可以从语义3d网站下载纯文本标签？？
> > > 这是语义网站http://www.semantic3d.net/view_dbase.php?chl=2
> > > ![图片](https://user-images.githubusercontent.com/48703273/70401158-6b29a100-1a69-11ea-94cc-a6d613162d0b.png)
> > > [](http://www.semantic3d.net/view_dbase.php?chl=2)
> 
> 嗨，谢谢你的答复。我已经下载了。我应该放入哪个文件夹？

"The label files of the training files must be put in the same directory than the .txt files.", so SEMA3D_DIR/data/train.

**Comment by longmalongma** [comment]
> > > > > > 嗨，
> > > > > > “训练文件的标签文件必须与.txt文件放在同一目录中。”，所以SEMA3D_DIR /数据/火车。
> > > > > > 但是，您必须重新启动分区步骤。
> > > > > 
> > > > > 
> > > > > 非常感谢您的回答。我想问一下标签文件是否需要解压缩。
> > > > > 而且我不知道标签上面是否为空会导致此问题。
> > > > > 当我使用h5浏览打开domfountain_station3.h5时，标签的分支中没有任何内容。
> > > > 
> > > > 
> > > > 您好，您已经解决了这个问题，在哪里可以从语义3d网站下载纯文本标签？？
> > > > 这是语义网站http://www.semantic3d.net/view_dbase.php?chl=2
> > > > ![图片](https://user-images.githubusercontent.com/48703273/70401158-6b29a100-1a69-11ea-94cc-a6d613162d0b.png)
> > 
> > 
> > 嗨，谢谢你的答复。我已经下载了。我应该放入哪个文件夹？
> 
> "The label files of the training files must be put in the same directory than the .txt files.", so SEMA3D_DIR/data/train.


> > > > > > 嗨，
> > > > > > “训练文件的标签文件必须与.txt文件放在同一目录中。”，所以SEMA3D_DIR /数据/火车。
> > > > > > 但是，您必须重新启动分区步骤。
> > > > > 
> > > > > 
> > > > > 非常感谢您的回答。我想问一下标签文件是否需要解压缩。
> > > > > 而且我不知道标签上面是否为空会导致此问题。
> > > > > 当我使用h5浏览打开domfountain_station3.h5时，标签的分支中没有任何内容。
> > > > 
> > > > 
> > > > 您好，您已经解决了这个问题，在哪里可以从语义3d网站下载纯文本标签？？
> > > > 这是语义网站http://www.semantic3d.net/view_dbase.php?chl=2
> > > > ![图片](https://user-images.githubusercontent.com/48703273/70401158-6b29a100-1a69-11ea-94cc-a6d613162d0b.png)
> > 
> > 
> > 嗨，谢谢你的答复。我已经下载了。我应该放入哪个文件夹？
> 
> "The label files of the training files must be put in the same directory than the .txt files.", so SEMA3D_DIR/data/train.

I have put it as you said,but I still have this problem:
Traceback (most recent call last):
  File "learning/sema3d_dataset.py", line 139, in <module>
    preprocess_pointclouds(args.SEMA3D_PATH)
  File "learning/sema3d_dataset.py", line 103, in preprocess_pointclouds
    hard_labels = np.argmax(labels[:,1:],1)
IndexError: too many indices for array
do you know why?

**Comment by longmalongma** [comment]
![Screenshot from 2019-12-09 10-22-31](https://user-images.githubusercontent.com/40291722/70402506-9793ec00-1a6e-11ea-9ab5-7a25ca737b07.png)

**Comment by zzusunquan** [comment]
> > > > > > > 嗨，
> > > > > > > “训练文件的标签文件必须与.txt文件放在同一目录中。”，所以SEMA3D_DIR /数据/火车。
> > > > > > > 但是，您必须重新启动分区步骤。
> > > > > > 
> > > > > > 
> > > > > > 非常感谢您的回答。我想问一下标签文件是否需要解压缩。
> > > > > > 而且我不知道标签上面是否为空会导致此问题。
> > > > > > 当我使用H5浏览打开domfountain_station3.h5时，标签的分支中没有任何内容。
> > > > > 
> > > > > 
> > > > > 您好，您已经解决了这个问题，在哪里可以从语义3d网站下载纯文本标签？？
> > > > > 这是语义网站http://www.semantic3d.net/view_dbase.php?chl=2
> > > > > ![图片](https://user-images.githubusercontent.com/48703273/70401158-6b29a100-1a69-11ea-94cc-a6d613162d0b.png)
> > > 
> > > 
> > > 嗨，谢谢你的答复。我已经下载了。我应该放入该文件夹？
> > 
> > 
> > “培训文件的标签文件必须与.txt文件放在同一目录中。”，所以SEMA3D_DIR / data / train。
> 
> > > > > > > 嗨，
> > > > > > > “训练文件的标签文件必须与.txt文件放在同一目录中。”，所以SEMA3D_DIR /数据/火车。
> > > > > > > 但是，您必须重新启动分区步骤。
> > > > > > 
> > > > > > 
> > > > > > 非常感谢您的回答。我想问一下标签文件是否需要解压缩。
> > > > > > 而且我不知道标签上面是否为空会导致此问题。
> > > > > > 当我使用H5浏览打开domfountain_station3.h5时，标签的分支中没有任何内容。
> > > > > 
> > > > > 
> > > > > 您好，您已经解决了这个问题，在哪里可以从语义3d网站下载纯文本标签？？
> > > > > 这是语义网站http://www.semantic3d.net/view_dbase.php?chl=2
> > > > > ![图片](https://user-images.githubusercontent.com/48703273/70401158-6b29a100-1a69-11ea-94cc-a6d613162d0b.png)
> > > 
> > > 
> > > 嗨，谢谢你的答复。我已经下载了。我应该放入该文件夹？
> > 
> > 
> > “培训文件的标签文件必须与.txt文件放在同一目录中。”，所以SEMA3D_DIR / data / train。
> 
> 我已经按照您说的说了，但是我仍然有这个问题：
> 追溯（最近一次呼叫最近）：
> 在
> preprocess_pointclouds（args.SEMA3D_PATH）中的
> 文件“ learning / sema3d_dataset.py” ，第139行，文件“ learning / sema3d_dataset.py” ，第103行，在preprocess_pointclouds中
> hard_labels = np.argmax（labels [：，1：]，1）
> IndexError：数组索引过多，
> 您知道为什么吗？

you must relaunch the partition step , Because the labels data is written into the array during the partitioning process

**Comment by longmalongma** [comment]
> > > > > > > > 嗨，
> > > > > > > > “训练文件的标签文件必须与.txt文件放在同一目录中。”，所以SEMA3D_DIR /数据/火车。
> > > > > > > > 但是，您必须重新启动分区步骤。
> > > > > > > 
> > > > > > > 
> > > > > > > 非常感谢您的回答。我想问一下标签文件是否需要解压缩。
> > > > > > > 而且我不知道标签上面是否为空会导致此问题。
> > > > > > > 当我使用H5浏览打开domfountain_station3.h5时，标签的分支中没有任何内容。
> > > > > > 
> > > > > > 
> > > > > > 您好，您已经解决了这个问题，在哪里可以从语义3d网站下载纯文本标签？？
> > > > > > 这是语义网站http://www.semantic3d.net/view_dbase.php?chl=2
> > > > > > ![图片](https://user-images.githubusercontent.com/48703273/70401158-6b29a100-1a69-11ea-94cc-a6d613162d0b.png)
> > > > 
> > > > 
> > > > 嗨，谢谢你的答复。我已经下载了。我应该放入该文件夹？
> > > 
> > > 
> > > “培训文件的标签文件必须与.txt文件放在同一目录中。”，所以SEMA3D_DIR / data / train。
> > 
> > 
> > > > > > > > 嗨，
> > > > > > > > “训练文件的标签文件必须与.txt文件放在同一目录中。”，所以SEMA3D_DIR /数据/火车。
> > > > > > > > 但是，您必须重新启动分区步骤。
> > > > > > > 
> > > > > > > 
> > > > > > > 非常感谢您的回答。我想问一下标签文件是否需要解压缩。
> > > > > > > 而且我不知道标签上面是否为空会导致此问题。
> > > > > > > 当我使用H5浏览打开domfountain_station3.h5时，标签的分支中没有任何内容。
> > > > > > 
> > > > > > 
> > > > > > 您好，您已经解决了这个问题，在哪里可以从语义3d网站下载纯文本标签？？
> > > > > > 这是语义网站http://www.semantic3d.net/view_dbase.php?chl=2
> > > > > > ![图片](https://user-images.githubusercontent.com/48703273/70401158-6b29a100-1a69-11ea-94cc-a6d613162d0b.png)
> > > > 
> > > > 
> > > > 嗨，谢谢你的答复。我已经下载了。我应该放入该文件夹？
> > > 
> > > 
> > > “培训文件的标签文件必须与.txt文件放在同一目录中。”，所以SEMA3D_DIR / data / train。
> > 
> > 
> > 我已经按照您说的说了，但是我仍然有这个问题：
> > 追溯（最近一次呼叫最近）：
> > 在
> > preprocess_pointclouds（args.SEMA3D_PATH）中的
> > 文件“ learning / sema3d_dataset.py” ，第139行，文件“ learning / sema3d_dataset.py” ，第103行，在preprocess_pointclouds中
> > hard_labels = np.argmax（labels [：，1：]，1）
> > IndexError：数组索引过多，
> > 您知道为什么吗？
> 
> you must relaunch the partition step , Because the labels data is written into the array during the partitioning process

I have uploaded my SEMA3D_DIR/data/train, is it correct?

**Comment by zzusunquan** [comment]
> > > > > > > > > 嗨，
> > > > > > > > > “训练文件的标签文件必须与.txt文件放在同一目录中。”，所以SEMA3D_DIR /数据/火车。
> > > > > > > > > 但是，您必须重新启动分区步骤。
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 非常感谢您的回答。我想问一下标签文件是否需要解压缩。
> > > > > > > > 而且我不知道标签上面是否为空会导致此问题。
> > > > > > > > 当我使用H5浏览打开domfountain_station3.h5时，标签的分支中没有任何内容。
> > > > > > > 
> > > > > > > 
> > > > > > > 您好，您已经解决了这个问题，在哪里可以从语义3d网站下载纯文本标签？？
> > > > > > > 这是语义网站http://www.semantic3d.net/view_dbase.php?chl=2
> > > > > > > ![图片](https://user-images.githubusercontent.com/48703273/70401158-6b29a100-1a69-11ea-94cc-a6d613162d0b.png)
> > > > > 
> > > > > 
> > > > > 嗨，谢谢你的答复。我已经下载了。我应该放入该文件夹？
> > > > 
> > > > 
> > > > “培训文件的标签文件必须与.txt文件放在同一目录中。”，所以SEMA3D_DIR / data / train。
> > > 
> > > 
> > > > > > > > > 嗨，
> > > > > > > > > “训练文件的标签文件必须与.txt文件放在同一目录中。”，所以SEMA3D_DIR /数据/火车。
> > > > > > > > > 但是，您必须重新启动分区步骤。
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 非常感谢您的回答。我想问一下标签文件是否需要解压缩。
> > > > > > > > 而且我不知道标签上面是否为空会导致此问题。
> > > > > > > > 当我使用H5浏览打开domfountain_station3.h5时，标签的分支中没有任何内容。
> > > > > > > 
> > > > > > > 
> > > > > > > 您好，您已经解决了这个问题，在哪里可以从语义3d网站下载纯文本标签？？
> > > > > > > 这是语义网站http://www.semantic3d.net/view_dbase.php?chl=2
> > > > > > > ![图片](https://user-images.githubusercontent.com/48703273/70401158-6b29a100-1a69-11ea-94cc-a6d613162d0b.png)
> > > > > 
> > > > > 
> > > > > 嗨，谢谢你的答复。我已经下载了。我应该放入该文件夹？
> > > > 
> > > > 
> > > > “培训文件的标签文件必须与.txt文件放在同一目录中。”，所以SEMA3D_DIR / data / train。
> > > 
> > > 
> > > 我已经按照您说的说了，但是我仍然有这个问题：
> > > 追溯（最近一次呼叫最近）：
> > > 在
> > > preprocess_pointclouds（args.SEMA3D_PATH）中的
> > > 文件“ learning / sema3d_dataset.py” ，第139行，文件“ learning / sema3d_dataset.py” ，第103行，在preprocess_pointclouds中
> > > hard_labels = np.argmax（labels [：，1：]，1）
> > > IndexError：数组索引过多，
> > > 您知道为什么吗？
> > 
> > 
> > you must relaunch the partition step , Because the labels data is written into the array during the partitioning process
> 
> I have uploaded my SEMA3D_DIR/data/train, is it correct?

Yes

**Comment by longmalongma** [comment]
> > > > > > > > 嗨，
> > > > > > > > “训练文件的标签文件必须与.txt文件放在同一目录中。”，所以SEMA3D_DIR /数据/火车。
> > > > > > > > 但是，您必须重新启动分区步骤。
> > > > > > > 
> > > > > > > 
> > > > > > > 非常感谢您的回答。我想问一下标签文件是否需要解压缩。
> > > > > > > 而且我不知道标签上面是否为空会导致此问题。
> > > > > > > 当我使用H5浏览打开domfountain_station3.h5时，标签的分支中没有任何内容。
> > > > > > 
> > > > > > 
> > > > > > 您好，您已经解决了这个问题，在哪里可以从语义3d网站下载纯文本标签？？
> > > > > > 这是语义网站http://www.semantic3d.net/view_dbase.php?chl=2
> > > > > > ![图片](https://user-images.githubusercontent.com/48703273/70401158-6b29a100-1a69-11ea-94cc-a6d613162d0b.png)
> > > > 
> > > > 
> > > > 嗨，谢谢你的答复。我已经下载了。我应该放入该文件夹？
> > > 
> > > 
> > > “培训文件的标签文件必须与.txt文件放在同一目录中。”，所以SEMA3D_DIR / data / train。
> > 
> > 
> > > > > > > > 嗨，
> > > > > > > > “训练文件的标签文件必须与.txt文件放在同一目录中。”，所以SEMA3D_DIR /数据/火车。
> > > > > > > > 但是，您必须重新启动分区步骤。
> > > > > > > 
> > > > > > > 
> > > > > > > 非常感谢您的回答。我想问一下标签文件是否需要解压缩。
> > > > > > > 而且我不知道标签上面是否为空会导致此问题。
> > > > > > > 当我使用H5浏览打开domfountain_station3.h5时，标签的分支中没有任何内容。
> > > > > > 
> > > > > > 
> > > > > > 您好，您已经解决了这个问题，在哪里可以从语义3d网站下载纯文本标签？？
> > > > > > 这是语义网站http://www.semantic3d.net/view_dbase.php?chl=2
> > > > > > ![图片](https://user-images.githubusercontent.com/48703273/70401158-6b29a100-1a69-11ea-94cc-a6d613162d0b.png)
> > > > 
> > > > 
> > > > 嗨，谢谢你的答复。我已经下载了。我应该放入该文件夹？
> > > 
> > > 
> > > “培训文件的标签文件必须与.txt文件放在同一目录中。”，所以SEMA3D_DIR / data / train。
> > 
> > 
> > 我已经按照您说的说了，但是我仍然有这个问题：
> > 追溯（最近一次呼叫最近）：
> > 在
> > preprocess_pointclouds（args.SEMA3D_PATH）中的
> > 文件“ learning / sema3d_dataset.py” ，第139行，文件“ learning / sema3d_dataset.py” ，第103行，在preprocess_pointclouds中
> > hard_labels = np.argmax（labels [：，1：]，1）
> > IndexError：数组索引过多，
> > 您知道为什么吗？
> 
> you must relaunch the partition step , Because the labels data is written into the array during the partitioning process

can you uploaded your SEMA3D_DIR/data/train directory？

**Comment by zzusunquan** [comment]
> > > > > > > > > 嗨，
> > > > > > > > > “训练文件的标签文件必须与.txt文件放在同一目录中。”，所以SEMA3D_DIR /数据/火车。
> > > > > > > > > 但是，您必须重新启动分区步骤。
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 非常感谢您的回答。我想问一下标签文件是否需要解压缩。
> > > > > > > > 而且我不知道标签上面是否为空会导致此问题。
> > > > > > > > 当我使用H5浏览打开domfountain_station3.h5时，标签的分支中没有任何内容。
> > > > > > > 
> > > > > > > 
> > > > > > > 您好，您已经解决了这个问题，在哪里可以从语义3d网站下载纯文本标签？？
> > > > > > > 这是语义网站http://www.semantic3d.net/view_dbase.php?chl=2
> > > > > > > ![图片](https://user-images.githubusercontent.com/48703273/70401158-6b29a100-1a69-11ea-94cc-a6d613162d0b.png)
> > > > > 
> > > > > 
> > > > > 嗨，谢谢你的答复。我已经下载了。我应该放入该文件夹？
> > > > 
> > > > 
> > > > “培训文件的标签文件必须与.txt文件放在同一目录中。”，所以SEMA3D_DIR /数据/火车。
> > > 
> > > 
> > > > > > > > > 嗨，
> > > > > > > > > “训练文件的标签文件必须与.txt文件放在同一目录中。”，所以SEMA3D_DIR /数据/火车。
> > > > > > > > > 但是，您必须重新启动分区步骤。
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 非常感谢您的回答。我想问一下标签文件是否需要解压缩。
> > > > > > > > 而且我不知道标签上面是否为空会导致此问题。
> > > > > > > > 当我使用H5浏览打开domfountain_station3.h5时，标签的分支中没有任何内容。
> > > > > > > 
> > > > > > > 
> > > > > > > 您好，您已经解决了这个问题，在哪里可以从语义3d网站下载纯文本标签？？
> > > > > > > 这是语义网站http://www.semantic3d.net/view_dbase.php?chl=2
> > > > > > > ![图片](https://user-images.githubusercontent.com/48703273/70401158-6b29a100-1a69-11ea-94cc-a6d613162d0b.png)
> > > > > 
> > > > > 
> > > > > 嗨，谢谢你的答复。我已经下载了。我应该放入该文件夹？
> > > > 
> > > > 
> > > > “培训文件的标签文件必须与.txt文件放在同一目录中。”，所以SEMA3D_DIR /数据/火车。
> > > 
> > > 
> > > 我已经按照您说的说了，但是我仍然有这个问题：
> > > 重新（最近一次呼叫最近）：
> > > 在
> > > preprocess_pointclouds（args.SEMA3D_PATH）中的
> > > 文件“ learning / sema3d_dataset.py”，第139行，文件“ learning / sema3d_dataset.py” ，，第103行，在preprocess_pointclouds中
> > > hard_labels = np.argmax（标签[：，1：]，1）
> > > IndexError：排序索引过多，
> > > 您知道为什么吗？
> > 
> > 
> > 您必须重新启动分区步骤，因为标签数据是在分区过程中写入数组的
> 
> 您可以上传SEMA3D_DIR / data / train目录吗？

![image](https://user-images.githubusercontent.com/48703273/70403042-716f4b80-1a70-11ea-99ff-24a6fdb45111.png)

**Comment by longmalongma** [comment]
> > > > > > > > > > 嗨，
> > > > > > > > > > “训练文件的标签文件必须与.txt文件放在同一目录中。”，所以SEMA3D_DIR /数据/火车。
> > > > > > > > > > 但是，您必须重新启动分区步骤。
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 非常感谢您的回答。我想问一下标签文件是否需要解压缩。
> > > > > > > > > 而且我不知道标签上面是否为空会导致此问题。
> > > > > > > > > 当我使用H5浏览打开domfountain_station3.h5时，标签的分支中没有任何内容。
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 您好，您已经解决了这个问题，在哪里可以从语义3d网站下载纯文本标签？？
> > > > > > > > 这是语义网站http://www.semantic3d.net/view_dbase.php?chl=2
> > > > > > > > ![图片](https://user-images.githubusercontent.com/48703273/70401158-6b29a100-1a69-11ea-94cc-a6d613162d0b.png)
> > > > > > 
> > > > > > 
> > > > > > 嗨，谢谢你的答复。我已经下载了。我应该放入该文件夹？
> > > > > 
> > > > > 
> > > > > “培训文件的标签文件必须与.txt文件放在同一目录中。”，所以SEMA3D_DIR /数据/火车。
> > > > 
> > > > 
> > > > > > > > > > 嗨，
> > > > > > > > > > “训练文件的标签文件必须与.txt文件放在同一目录中。”，所以SEMA3D_DIR /数据/火车。
> > > > > > > > > > 但是，您必须重新启动分区步骤。
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 非常感谢您的回答。我想问一下标签文件是否需要解压缩。
> > > > > > > > > 而且我不知道标签上面是否为空会导致此问题。
> > > > > > > > > 当我使用H5浏览打开domfountain_station3.h5时，标签的分支中没有任何内容。
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 您好，您已经解决了这个问题，在哪里可以从语义3d网站下载纯文本标签？？
> > > > > > > > 这是语义网站http://www.semantic3d.net/view_dbase.php?chl=2
> > > > > > > > ![图片](https://user-images.githubusercontent.com/48703273/70401158-6b29a100-1a69-11ea-94cc-a6d613162d0b.png)
> > > > > > 
> > > > > > 
> > > > > > 嗨，谢谢你的答复。我已经下载了。我应该放入该文件夹？
> > > > > 
> > > > > 
> > > > > “培训文件的标签文件必须与.txt文件放在同一目录中。”，所以SEMA3D_DIR /数据/火车。
> > > > 
> > > > 
> > > > 我已经按照您说的说了，但是我仍然有这个问题：
> > > > 重新（最近一次呼叫最近）：
> > > > 在
> > > > preprocess_pointclouds（args.SEMA3D_PATH）中的
> > > > 文件“ learning / sema3d_dataset.py”，第139行，文件“ learning / sema3d_dataset.py” ，，第103行，在preprocess_pointclouds中
> > > > hard_labels = np.argmax（标签[：，1：]，1）
> > > > IndexError：排序索引过多，
> > > > 您知道为什么吗？
> > > 
> > > 
> > > 您必须重新启动分区步骤，因为标签数据是在分区过程中写入数组的
> > 
> > 
> > 您可以上传SEMA3D_DIR / data / train目录吗？
> 
> ![image](https://user-images.githubusercontent.com/48703273/70403042-716f4b80-1a70-11ea-99ff-24a6fdb45111.png)

Thanks your help,I will try to run it again.

**Comment by longmalongma** [comment]
> > > > > > > > > > 嗨，
> > > > > > > > > > “训练文件的标签文件必须与.txt文件放在同一目录中。”，所以SEMA3D_DIR /数据/火车。
> > > > > > > > > > 但是，您必须重新启动分区步骤。
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 非常感谢您的回答。我想问一下标签文件是否需要解压缩。
> > > > > > > > > 而且我不知道标签上面是否为空会导致此问题。
> > > > > > > > > 当我使用H5浏览打开domfountain_station3.h5时，标签的分支中没有任何内容。
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 您好，您已经解决了这个问题，在哪里可以从语义3d网站下载纯文本标签？？
> > > > > > > > 这是语义网站http://www.semantic3d.net/view_dbase.php?chl=2
> > > > > > > > ![图片](https://user-images.githubusercontent.com/48703273/70401158-6b29a100-1a69-11ea-94cc-a6d613162d0b.png)
> > > > > > 
> > > > > > 
> > > > > > 嗨，谢谢你的答复。我已经下载了。我应该放入该文件夹？
> > > > > 
> > > > > 
> > > > > “培训文件的标签文件必须与.txt文件放在同一目录中。”，所以SEMA3D_DIR /数据/火车。
> > > > 
> > > > 
> > > > > > > > > > 嗨，
> > > > > > > > > > “训练文件的标签文件必须与.txt文件放在同一目录中。”，所以SEMA3D_DIR /数据/火车。
> > > > > > > > > > 但是，您必须重新启动分区步骤。
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 非常感谢您的回答。我想问一下标签文件是否需要解压缩。
> > > > > > > > > 而且我不知道标签上面是否为空会导致此问题。
> > > > > > > > > 当我使用H5浏览打开domfountain_station3.h5时，标签的分支中没有任何内容。
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 您好，您已经解决了这个问题，在哪里可以从语义3d网站下载纯文本标签？？
> > > > > > > > 这是语义网站http://www.semantic3d.net/view_dbase.php?chl=2
> > > > > > > > ![图片](https://user-images.githubusercontent.com/48703273/70401158-6b29a100-1a69-11ea-94cc-a6d613162d0b.png)
> > > > > > 
> > > > > > 
> > > > > > 嗨，谢谢你的答复。我已经下载了。我应该放入该文件夹？
> > > > > 
> > > > > 
> > > > > “培训文件的标签文件必须与.txt文件放在同一目录中。”，所以SEMA3D_DIR /数据/火车。
> > > > 
> > > > 
> > > > 我已经按照您说的说了，但是我仍然有这个问题：
> > > > 重新（最近一次呼叫最近）：
> > > > 在
> > > > preprocess_pointclouds（args.SEMA3D_PATH）中的
> > > > 文件“ learning / sema3d_dataset.py”，第139行，文件“ learning / sema3d_dataset.py” ，，第103行，在preprocess_pointclouds中
> > > > hard_labels = np.argmax（标签[：，1：]，1）
> > > > IndexError：排序索引过多，
> > > > 您知道为什么吗？
> > > 
> > > 
> > > 您必须重新启动分区步骤，因为标签数据是在分区过程中写入数组的
> > 
> > 
> > 您可以上传SEMA3D_DIR / data / train目录吗？
> 
> ![image](https://user-images.githubusercontent.com/48703273/70403042-716f4b80-1a70-11ea-99ff-24a6fdb45111.png)

Hello,I have relunched partition.py,then i run python learning/sema3d_dataset.py --SEMA3D_PATH SEMA3D_DIR,i still meet this problem:
 python learning/sema3d_dataset.py --SEMA3D_PATH SEMA3D_DIR
bildstein_station1.h5
bildstein_station3.h5
bildstein_station5.h5
domfountain_station1.h5
domfountain_station2.h5
domfountain_station3.h5
sg27_station1.h5
sg27_station2.h5
sg27_station4.h5
sg27_station5.h5
sg27_station9.h5
sg28_station4.h5
station1_xyz.h5
Traceback (most recent call last):
  File "learning/sema3d_dataset.py", line 139, in <module>
    preprocess_pointclouds(args.SEMA3D_PATH)
  File "learning/sema3d_dataset.py", line 103, in preprocess_pointclouds
    hard_labels = np.argmax(labels[:,1:],1)
IndexError: too many indices for array
can you help me  again?

**Comment by loicland** [comment]
Hi.

`station1_xyz.h5` is not a correct filename.

Did you modify the `untermeadenbrunnen_station1_xyz.txt` file name somehow? If not redownload it and unzip it again.

**Comment by longmalongma** [comment]
> Hi.
> 
> `station1_xyz.h5` is not a correct filename.
> 
> Did you modify the `untermeadenbrunnen_station1_xyz.txt` file name somehow? If not redownload it and unzip it again.

Thanks for you reply,I didn't modify any files,ｄo you mean redownload untermeadenbrunnen_station1_xyz.txt,and relunch partion.py and sema3d_dataset.py?

**Comment by loicland** [comment]
Check in the features and superpoint graph folders if there is indeed a untermeadenbrunnen_station1.h5 file in each. If there is a station1_xyz.h5 it means something went wrong in the name parsing.

**Comment by longmalongma** [comment]
> Check in the features and superpoint graph folders if there is indeed a untermeadenbrunnen_station1.h5 file in each. If there is a station1_xyz.h5 it means something went wrong in the name parsing.

![image](https://user-images.githubusercontent.com/40291722/70416533-3c77ee80-1a9a-11ea-87cd-7cedf3996cd1.png)
I find the neugasse_station1_xyz_intensity_rgb.labels and station1_xyz_intensity_rgb.txt do match,need i modify station1_xyz_intensity_rgb.txt to neugasse_station1_xyz_intensity_rgb.txt?

**Comment by kxhit** [comment]
I modify "station1_xyz.txt" to "neugasse_station1_xyz_intensity_rgb.txt" and everything goes well.
