### ISSUE TITLE
make: *** No targets specified and no makefile found.  Stop.

### ISSUE THREAD

**Issue by FengzhuoZhang** [loicland/superpoint_graph#171]
![12](https://user-images.githubusercontent.com/28057968/68459180-9db06600-023f-11ea-92c3-442e63b1d061.JPG)
I have run the cmake file code successfully but when running "make". It could not find the makefile.

**Comment by loicland** [comment]
Is a makefile built in `/partition/ply_c`?

Also what did you set CONDA_ENV to?

**Comment by FengzhuoZhang** [comment]
![13](https://user-images.githubusercontent.com/28057968/68526307-48468880-0315-11ea-8c1e-cb8bcea9e6ee.JPG)
I do not find the makefile in /partition/ply_c.
I set CONDAENV=E:/Anaconda

**Comment by loicland** [comment]
Hi,

it seems like the cmake worked. What is your version of cmake? It needs 3.7 I think to compile.

I have never personnaly used Cmake on windows so I can only help you so much.
