### ISSUE TITLE
increase importance of verticality (heuristic)

### ISSUE THREAD

**Issue by zzusunquan** [loicland/superpoint_graph#172]
Hi
  In reading your partition.py, when you create the spg h5 file, you multiply the verticality feature by 2 to increase the importance of verticality. Can you explain this principle? 
`geof = libply_c.compute_geof(xyz, target_fea, args.k_nn_geof).astype('float32')`
How can I view the definition of computr_geof in libply_c ?

**Comment by loicland** [comment]
Hi,

this is purely heuristic. my reasonning was: linearity, verticality and scattering are redundant as their sum is 1 (simplex-valued), so I need to increase the relative importance of the verticality. It might be different for different datasets.

Empirically it worked better as well. if you want something more principled, use our learned partition framework.
