### ISSUE TITLE
compensate the lack of rgb values

### ISSUE THREAD

**Issue by medif** [loicland/superpoint_graph#174]
Hi Mr Loic,
Thank you for the great work about the superpoints graph, ​ I am trying to apply it to make semantic segmentation for outdoors scenes and i have interest in some classes rather the others(building, doors, sidewalks, roads, traffic signs),but my training dataset is without RGB values so i wonder if you have any suggestions to compensate the lack of this information? adding new features for example?
Thank you for your response

**Comment by loicland** [comment]
Hi,

doors/facade will be hard to detect without radiometry, the other should work ok (eventhough sidewalks are always tricky).

If you are using LiDAR-generated point clouds, I would suggest to use the (normalized) reflectance/intensity.
