### ISSUE TITLE
Questions about the significance of applying spg to your own scanned data：

### ISSUE THREAD

**Issue by zzusunquan** [loicland/superpoint_graph#176]
Hi:
  I did the following work：
1）Scan one station point cloud data by yourself, try to imitate the format of semantic3d，The specific values of the data are shown below (x, y, z, intensity, r.g.b)
![image](https://user-images.githubusercontent.com/48703273/69688018-d2596400-10ff-11ea-8557-7e0c321237ad.png)

2）I put this data into test_reduced and used it as a test set for label prediction，Visualize the partition results and prediction results，The specific partition results are shown in the following figure
The following figure is in order geof.ply partition.ply pred.ply rgb.ply spg.py
![image](https://user-images.githubusercontent.com/48703273/69688041-e1d8ad00-10ff-11ea-8ad5-01cf00e70bef.png)
![image](https://user-images.githubusercontent.com/48703273/69688046-e69d6100-10ff-11ea-9b97-511f7090abe2.png)
![image](https://user-images.githubusercontent.com/48703273/69688058-ebfaab80-10ff-11ea-9c84-8000fe373788.png)
![image](https://user-images.githubusercontent.com/48703273/69688064-f026c900-10ff-11ea-881b-321b6a71fc65.png)
![image](https://user-images.githubusercontent.com/48703273/69688075-f5841380-10ff-11ea-817d-99282c1ac99c.png)
This spg file is open without anything
The result seems to be very good. I originally planned to do a supplementary annotation work, but suddenly realized that there was no such innovation，Just making a comment in an area that no one has commented on, this will be meaningless.
So I want to take the liberty to ask you, is there any article about annotations, or do you think it makes sense for me to do so (if possible, if possible)

**Comment by loicland** [comment]
Hi,

I am not aware of programs that specifically helps to do manual annotation. you can use CloudCompare and select bounding boxes however, I think it is the easiest way of going about it.
