### ISSUE TITLE
error in cmake

### ISSUE THREAD

**Issue by typhoonlee** [loicland/superpoint_graph#177]
Hello ，i encountered a problem during compilation.
Instead of using conda to install boost, I used source code compilation, and the version is boost_1.69.0。
The obtained library is libboost_python27, I don't know if the library in your CMakeList.txt file is libboost_python36 or libboost_python27
I hope you can reply to me, and I wish you a successful research

**Comment by loicland** [comment]
I have never tried with python 2.7 but I don't recommend that you do. It should be libboost_python36, try to manually specify the version if need be.

**Comment by typhoonlee** [comment]
Thank you very much. It works.
But there was an error again during make

**Comment by typhoonlee** [comment]
fatal error: numpy/ndarrayobject.h: No such file or directory
How should I do

**Comment by loicland** [comment]
Please check issue #13, #36 and #132. tell me if none of the fixes works for you.

**Comment by typhoonlee** [comment]
Thank you very much, it has been fixed, after executing make, the following display：
[100%] Linking CXX shared library libply_c.so
[100%] Built target ply_c
Did this compile successfully?
