### ISSUE TITLE
Partitioning based on geometric features only

### ISSUE THREAD

**Issue by bach-zouk** [loicland/superpoint_graph#18]
Hi, 

Running your cut-pursuit purely on geometric features of point cloud, without any RGB, produces the following output:

Graph 1571 vertices and 37656 edges and observation of dimension 4
Iteration   1 -    1 components - Saturation 100.0 % - Quadratic Energy  nan % - Timer  0.025178
All components are saturated

I think this means the problem(graph) is ill conditioned so no iterations and thus, a degenerate solution? or maybe I am doing something silly.

Thanks for your reply.

**Comment by loicland** [comment]
Hi,

first are you running the `partition.ply` method or something homemade?

It seems that  the quadratic energy is NaN. That could indicate that some of your obeservation are NaN, which would kill the process. Are you computing them yourself or using the methods in the git?

**Comment by bach-zouk** [comment]
yes, running your source code partition.py with other functions in provider.py and graph.py, nothing homemade. I  check the graph input values to see if there is an NaN and get back.  Thanks

**Comment by bach-zouk** [comment]
Value of lambda_0 in ply_c:compute_geof is 0 which makes the rest go NaN. Debugging python wrapper of C++ code is slow with print :)

**Comment by loicland** [comment]
What point cloud are you applying the `compute_geof` function to? `lambda[0]=0` means that the spatial covariance matrix is 0, i.e. you have 45 points in the same exact position. Which is impossible since it should have been filtered out by the pruning.

maybe post here the point cloud (it seems very small? 1570 points) and I'll try to see what went wrong.

**Comment by bach-zouk** [comment]
Thank you for your reply. I think it should help to resolve the issue else I will post the point cloud

**Comment by loicland** [comment]
Updated the repo to make partitioning without rgb easier.

**Comment by ardianumam** [comment]
> What point cloud are you applying the `compute_geof` function to? `lambda[0]=0` means that the spatial covariance matrix is 0, i.e. you have 45 points in the same exact position. Which is impossible since it should have been filtered out by the pruning.
> 
> maybe post here the point cloud (it seems very small? 1570 points) and I'll try to see what went wrong.

Hi,

I'm trying to partition [ShapeNet part dataset](https://www.researchgate.net/profile/Yongcheng-Liu/publication/332497055/figure/fig2/AS:748992291930112@1555585086201/Segmentation-examples-on-ShapeNet-part-benchmark.ppm) with number of points = 1024, and `libply_c.compute_geof` returns me NaN values. Any direction? Thanks.

**Comment by loicland** [comment]
is it only nan values or just some?

**Comment by ardianumam** [comment]
> is it only nan values or just some?

The returned `geof` has shape of [1024, 4], and the number of NaN elements is 4096 (which is 1024*4). So, all are NaN values.

**Comment by loicland** [comment]
Can you try with this repo (part of the newer release of SPG planned in a couple weeks);

https://github.com/drprojects/point_geometric_features

**Comment by ardianumam** [comment]
> Can you try with this repo (part of the newer release of SPG planned in a couple weeks);
> 
> https://github.com/drprojects/point_geometric_features

Thanks! Will try that out

**Comment by loicland** [comment]
PS my student is updating the repo rihgt now to make it easier to compute the nn graph. Will let you know when done.

**Comment by wy9933** [comment]
> > Can you try with this repo (part of the newer release of SPG planned in a couple weeks);
> > https://github.com/drprojects/point_geometric_features
> 
> Thanks! Will try that out

Hi, have you solved the problem that all value of 'geof' are NaN?

**Comment by loicland** [comment]
Please post an issue on this repo `https://github.com/drprojects/point_geometric_features`  as their code solves a lots of the problem.

But typically, the NaN issues are due to the point cloud, eg points that are deduplicated, a NaN value somewhere, etc. I would start by inspecting it thoroughly.

**Comment by wy9933** [comment]
> Please post an issue on this repo `https://github.com/drprojects/point_geometric_features` as their code solves a lots of the problem.
> 
> But typically, the NaN issues are due to the point cloud, eg points that are deduplicated, a NaN value somewhere, etc. I would start by inspecting it thoroughly.

Thanks, I will check out my data and code, sorry to bother. 😃
