### ISSUE TITLE
IndexError: too many indices for array

### ISSUE THREAD

**Issue by longmalongma** [loicland/superpoint_graph#180]
Hello,when i run python learning/sema3d_dataset.py --SEMA3D_PATH SEMA3D_DIR,
i meet this problem:
IndexError: too many indices for array
how to ｏrganize "labes" files have download from website? Could you be more specific？looking forward your reply.

**Comment by loicland** [comment]
In /train you should have all the training point clouds and labels files in text form (unzipped).
