### ISSUE TITLE
Questions about learning/spg.py 214 line changes

### ISSUE THREAD

**Issue by zzusunquan** [loicland/superpoint_graph#183]
Hi Loicland:
    I asked you before that if my training data is 8 columns, except XYZRGBI which has one more column, you told me that I only need to modify 214 rows of learning/spg.py. However, I found that after the combination of the superpoints, the parsed/train/**.h5 file still contains 11 columns of data. Compared with the semantic original data, the extra column of data I created disappears.How should this situation be handled ?

**Comment by loicland** [comment]
Hi,

Either you change how the parsed file are read (in `learning/spg.py`) or how they are written.

if you want to change how they are writte, the `parsed` file is written in the preprocess_point cloud method. Each dataset should have its own. For S3DIS for example, it is being written line 146 of `learning/s3dis_dataset.py`.
