### ISSUE TITLE
About the density of the testing data

### ISSUE THREAD

**Issue by medif** [loicland/superpoint_graph#185]
Hi,
Thank you for the great work, i have a question about the width of the voxel when we choose 0.05 what is the density of the data per cm ? also i want to know if it is possible to have different densities for the training and for the testing?, if not is there any way to keep a very height density for the testing data set??
THank you in advance

**Comment by loicland** [comment]
Hi,

voxelizing does three things:
- prevent using redundant information in clouds with highly variable density (for example, when an object is close to a sensor)
- homogeneize the pint clouds and help the cloud emebdder to learn the distributions of points inside superpoints
- decrease the geometric and radiometric noise which helps the (handcrafted) partition

I would not recommend at all using different densities in training and test set. 

However, you can do the training and inference with a voxelized data and then interpolate the results to your full input cloud. See `interpolate_labels_batch` line 607 of `partition/provider` and `partition/write_Semantic3d.py`.

**Comment by medif** [comment]
Thank you
