### ISSUE TITLE
Strange value of the test accuracy

### ISSUE THREAD

**Issue by LZDSJTU** [loicland/superpoint_graph#19]
I run
CUDA_VISIBLE_DEVICES=0 python learning/main.py --dataset sema3d --SEMA3D_PATH $SEMA3D_DIR --db_test_name testred --db_train_name trainval \
--epochs 500 --lr_steps '[350, 400, 450]' --test_nth_epoch 100 --model_config 'gru_10,f_8' --ptn_nfeat_stn 11 \
--nworkers 2 --odir "results/sema3d/trainval_best"
And I use epochs 100
After training, the result is 
[{"avg_iou_test": 0.0, "acc_test": 1.1444885172178565, "epoch": 0, "oacc_test": 0.0, "per_class_iou_test": {"veget_hi": 0.0, "building": 0.0, "artefact": 0.0, "veget_low": 0.0, "scape": 0.0, "terrain_man": 0.0, "terrain_nature": 0.0, "cars": 0.0}, "avg_acc_test": 0.0}]
The test accuracy is very low and many metric is zeros.
I want to ask if I make some mistakes during training.
Thank you

**Comment by LZDSJTU** [comment]
However, I visualize the result. I find that it looks not bad. So I wonder if there are some mistakes of the metrics.

**Comment by loicland** [comment]
Hi. The accuracy is computed on the reduced test here, for which there are no ground truth available, hence the strange results of accuracy. So this is normal!

What do you mean "I use epochs 100"? On sema3d you should use at least 400 epochs.
