### ISSUE TITLE
Outdoor scene

### ISSUE THREAD

**Issue by abhigoku10** [loicland/superpoint_graph#193]
@loicland @nicolas-chaulet @mys007  hi team wonderful and thanks for sharing it , can we apply your method to outdoor scene to segment stationary objects ?

**Comment by loicland** [comment]
Hi,

the code worked on semantic3d and vkitti3d which are both outdoor so yes!

Note the hyperparameterization will depend on your sensor. If you are using a dense liDAR use semantic3d, if it is a velodyne use vkitti3d as a template.
