### ISSUE TITLE
Compile the libply_c and libcp libraries on windows

### ISSUE THREAD

**Issue by fclairec** [loicland/superpoint_graph#196]
Hi,
Thanks a lot for sharing your nice work!
I am having troubbles getting the Cmake to compile properly. Do you have experience in how to set up the command on windows? 

![image](https://user-images.githubusercontent.com/59439696/73962010-f3afab00-490d-11ea-9566-09bfab74a4d1.png)

I updated Boost to the newest version and still there is the same message.
I am not familiar to the dependancies of Cmake so I am not sure if I am simply missing a little thing. 

I would greatly appreciate your help, thank you !

**Comment by loicland** [comment]
Hi,

I have never tried personally to compile the library on windows myself.

See [this guide](https://www.boost.org/doc/libs/1_54_0/libs/python/doc/building.html) if it helps.

**Comment by fclairec** [comment]
Thank you for the tip
