### ISSUE TITLE
how to modify the prune function 

### ISSUE THREAD

**Issue by medif** [loicland/superpoint_graph#198]
Hi,
I have a dataset without rgb values with 9 classes labeled and the format is .npy (type float32)
I changed the line like:
xyz,labels = libply_c.prune(xyz, args.voxel_width,np.zeros(xyz.shape,dtype='u1'),labels,np.zeros(1, dtype='uint8'),9,0)
but it throw an error
IndexError: vector::_M_range_check: __n (which is 64) >= this->size() (which is 10)

, any suggestions please
Thank you

**Comment by loicland** [comment]
Did you figure it out?

Otherwise please report the value of .shape and dtype for xyz and labels.

**Comment by medif** [comment]
Hi, 
It was working fine until i changed my data structure. Now i am using 3 classes (0 as unlabled )

![Capture](https://user-images.githubusercontent.com/55558657/75910630-2e790600-5e1c-11ea-8a9c-e35a1b9a32f3.PNG)



 Can you help me please

**Comment by loicland** [comment]
why is the label type 'f2'? it should be 'uint8'.
