### ISSUE TITLE
Can't file .hpy file

### ISSUE THREAD

**Issue by amandaloh16** [loicland/superpoint_graph#20]
Was having an issue finding a predictions_testred.h5 hpy file: realized a new trainval_best folder is generated even though the command: python partition/write_Semantic3d.py --SEMA3D_PATH $SEMA3D_DIR --odir "results/sema3d/best" --db_test_name testred specifies a different path in the folder 'best'

Found this command to work which implies predictions_testred.h5 is in **trainval_best** folder and not **best** folder. Not sure if this is a problem other people are facing? If anyone  has this issue as well this is the solution I found.
`amanda@amanda-Precision-Tower-5810:~/superpoint_graph$ python partition/write_Semantic3d.py --SEMA3D_PATH /home/amanda/Semantic3D/ --odir "results/sema3d/trainval_best" --db_test_name testred`

`OSError: Unable to open file (unable to open file: name = './results/sema3d/best/predictions_testred.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
`

**Comment by loicland** [comment]
Hi,
You should adapt ```--odir``` to chose the model you want, you can also rename them. I changed it in the instruction to make it so that ```write``` uses the inference from the model trained on the full train set (`train_val/best`) but feel free to rename them.

I am unsure I understand the rest of your message, do you have an error still? From what command?

**Comment by amandaloh16** [comment]
No, this is more a note to anyone else because I spent a lot of time debugging the issue why I was getting OSErrors because I thought the write folder was default the same as the read folder later.

**Comment by loicland** [comment]
I see. Thanks for pointing it out anyway, I changed the README so that it will be clearer.
