### ISSUE TITLE
Visualization of ground truth missing labels

### ISSUE THREAD

**Issue by renegades12** [loicland/superpoint_graph#205]
@loicland Hi, I ran the model on Semantic3D dataset, and after creating the superpoint .h5 file I ran the visualization command:
```bash
python partition/visualize.py --dataset sema3d --ROOT_PATH $s3d_path  --file_path 'train/domfountain_station1' --output_type g
```
to visualize the gt point cloud, however, the Point cloud I got looks like this:

![image](https://user-images.githubusercontent.com/61343266/79782788-33652b00-8372-11ea-8b7f-30e1643ab2be.png)
Is it right to get this subsampled one? or how to fix it? thanks!

**Comment by renegades12** [comment]
@loicland 
But when I ran this:
```bash
python partition/visualize.py --dataset sema3d --ROOT_PATH $s3d_path --file_path 'train/sg27_station9' --output_type g
```

I got the **"seems right"** gt file:

![image](https://user-images.githubusercontent.com/61343266/79783461-462c2f80-8373-11ea-874f-c01c348824bf.png)

**Comment by loicland** [comment]
The ground truth of semantic 3D is sparse, and only a heavily subsampled subset of points are annotated. Depending on the resolution and the voxelisation it can be more or less apparent. It also varies from cloud to cloud throughout the dataset.

If you really want to have a 'full' ground truth, you can use the interpolating functions `interpolate_labels`.

**Comment by renegades12** [comment]
@loicland thanks! that makes sense. in terms of using `interpolate_labels`, I tried to simply add an additional argument `--upsample 1` and then output the gt file, but the ply file looks the same, should I modify the code in the gt part, if so, then how to modify?

**Comment by loicland** [comment]
I haven't coded the ground truth upsampling yet.
It would look like something like that in visualize.py:
```
if gt_out and bool(args.upsample):
    if args.dataset=='s3dis':
        #TODO
    elif args.dataset=='sema3d':
        data_file  = data_folder + file_name + ".txt"
        xyz_up, rgb_up = read_semantic3d_format(data_file, 0, '', 0, args.ver_batch)
    del rgb_up
    gt_up = interpolate_labels(xyz_up, xyz, label, args.ver_batch)
    print("writing the upsampled ground truth file...")
    prediction2ply(ply_file + "_gt_up.ply", xyz_up, gt_up +1, n_labels, args.dataset)
```

I can't test it out right now, let me know if you get stuck or if you manage to make it work.

**Comment by renegades12** [comment]
@loicland Hi, thanks for the code, I tried this out:

first, I set `ver_batch = 4`

Then after a long time of processing like this:
```
...
processing lines 44990624 to 44990628
processing lines 44990628 to 44990632
processing lines 44990632 to 44990636
processing lines 44990636 to 44990640
writing the upsampled ground truth file... 
```
the file I got `domfountain_station1_urban_trained_gt_up.ply` contains only 4 points, do you think there might be something wrong with the `ver_batch` size? or something else went wrong?

**Comment by renegades12** [comment]
@loicland Hi, thanks for the code, I tried this out:

first, I set `ver_batch = 4`

Then after a long time of processing like this:
```
...
processing lines 44990624 to 44990628
processing lines 44990628 to 44990632
processing lines 44990632 to 44990636
processing lines 44990636 to 44990640
writing the upsampled ground truth file... 
```
the file I got `domfountain_station1_gt_up.ply` contains only 4 points, do you think there might be something wrong with the `ver_batch` size? or something else went wrong?

**Comment by loicland** [comment]
Hi,

ver_batch is the number of lines to be read simultaneously. It should be around 5.000.000 rather than 4!

In case this doesn't fix your issue, could printthe following sizes:
```
print(xyz_up.shape)
print(xyz.shape)
print(label.shape)
```

**Comment by renegades12** [comment]
@loicland Hi, thanks for the advice! I changed the size to 5,000,000 and print out the size
![image](https://user-images.githubusercontent.com/61343266/80448517-1f5f9180-894f-11ea-9846-6f3bb08a1294.png)


However, the output still looks wired:

![image](https://user-images.githubusercontent.com/61343266/80448587-59c92e80-894f-11ea-9cfd-bbe6e087806e.png)

So, I debugged the code and finally find out the cause:

Since there's no `label` in the file `visualize.py` so instead I use the `labels` from `geof, xyz, rgb, graph_nn, labels = read_features(fea_file)`, but the `labels` file looks like this:

![image](https://user-images.githubusercontent.com/61343266/80448227-2fc33c80-894e-11ea-8a21-6b2159ad7d59.png)
Thus in the function `interpolate_labels`, labels will always be 0 
![image](https://user-images.githubusercontent.com/61343266/80448725-c9d7b480-894f-11ea-9ece-8895a207a075.png)
![image](https://user-images.githubusercontent.com/61343266/80448192-13270480-894e-11ea-9d46-f22f0d3e3f3a.png)
But as I look into the `labels` read from feature file, I was confused that there's a `10` in the array (index 211), but I expect the max of sem3d as 8
![image](https://user-images.githubusercontent.com/61343266/80448567-474ef500-894f-11ea-8ea2-8acb91b55273.png)

Do these look fine? or do you suggest which part did I made a mistake?
Looking forward to your suggestions!

**Comment by loicland** [comment]
Hi!

We are releasing a new version of SuperPoint Graph called SuperPoint Transformer (SPT).

https://github.com/drprojects/superpoint_transformer

It is better in any way:

| ✨ SPT in numbers ✨ |
| :---: |
| 📊 **SOTA results:** 76.0 mIoU S3DIS 6-Fold, 63.5 mIoU on KITTI-360 Val, 79.6 mIoU on DALES  |
| 🦋 **212k parameters only!** | 
| ⚡ Trains on S3DIS in **3h on 1 GPU**| 
| ⚡ **Preprocessing is x7 faster than SPG!** |
| 🚀  **Easy install** (no more boost!)|

If you are interested in lightweight, high-performance 3D deep learning, you should check it out. In the meantime, we will finally retire SPG and stop maintaining this repo.
