### ISSUE TITLE
How can I compile libply_c and libcp in docker?

### ISSUE THREAD

**Issue by garryz94** [loicland/superpoint_graph#207]
Hi Loic, thanks for your brilliant work! 
Now I want to run this code in nvidia-docker. But I have problems  with compiling libply and libcp without anaconda. Do you know how to compile these two libraries in docker? Do I have to install ananconda in docker?

**Comment by loicland** [comment]
Hi,

sorry, I do not have experience with docker. As far as I know you do not need anaconda specifically to compile the c++ wrappers but only boost. Although virtual environments makes this easier for sure.

**Comment by garryz94** [comment]
> Hi,
> 
> sorry, I do not have experience with docker. As far as I know you do not need anaconda specifically to compile the c++ wrappers but only boost. Although virtual environments makes this easier for sure.

Thanks for your quick reply anyway! Hope someone with docker experience can help me out!
