### ISSUE TITLE
Do you use rgb to generate features during preprocessing?

### ISSUE THREAD

**Issue by LZDSJTU** [loicland/superpoint_graph#21]
I want to train without rgb and I succeed.
I want to know that if you use rgb to generate other features when preprocessing the original data? Because if you use rgb, maybe I need to re-generate the spg and feature files. If you do not use rgb during preprocessing, I can just omit the rgb value and train.

**Comment by loicland** [comment]
We do not use the rgb values to generate the spgs for semantic3d, but use them for s3dis. You can easily change it line 156 of ```/partition/partition.py``` if need be.

What's crucial however is that you retrain the models from scratch for the inference with option ```--pc_attribs "xyzelpsv"```, as described in [issue#11](https://github.com/loicland/superpoint_graph/issues/11). Do not use our pretrained models without rgb as it will perform very badly.
