### ISSUE TITLE
Can you expose OA and mIoU for each category on the Vkitti dataset

### ISSUE THREAD

**Issue by longmalongma** [loicland/superpoint_graph#210]
Hi,thanks for your reply, Can you expose OA and mIoU for each category on the Vkitti dataset?looking forwarding to your reply.

**Comment by loicland** [comment]
`python learning/evaluate.py --dataset vkitti --odir results/vkitti/best --cvfold 123456` should give you a breakdown of OA and IoU by classes.

**Comment by longmalongma** [comment]
> `python learning/evaluate.py --dataset vkitti --odir results/vkitti/best --cvfold 123456` should give you a breakdown of OA and IoU by classes.
Thanks.

**Comment by longmalongma** [comment]
> `python learning/evaluate.py --dataset vkitti --odir results/vkitti/best --cvfold 123456` should give you a breakdown of OA and IoU by classes.

Have you recorded　IoU  of each category before?Can you just give me mIoU of each category of your model on the vKITTI dataset right here? I want to quote your paper in my paper and compare it with your algorithm for mIoU of each category.

**Comment by loicland** [comment]
Hi!

We are releasing a new version of SuperPoint Graph called SuperPoint Transformer (SPT).

https://github.com/drprojects/superpoint_transformer

It is better in any way:

| ✨ SPT in numbers ✨ |
| :---: |
| 📊 **SOTA results:** 76.0 mIoU S3DIS 6-Fold, 63.5 mIoU on KITTI-360 Val, 79.6 mIoU on DALES  |
| 🦋 **212k parameters only!** | 
| ⚡ Trains on S3DIS in **3h on 1 GPU**| 
| ⚡ **Preprocessing is x7 faster than SPG!** |
| 🚀  **Easy install** (no more boost!)|

If you are interested in lightweight, high-performance 3D deep learning, you should check it out. In the meantime, we will finally retire SPG and stop maintaining this repo.
