### ISSUE TITLE
How to replace your model with my own model to train and test on these data sets?

### ISSUE THREAD

**Issue by longmalongma** [loicland/superpoint_graph#213]
Thanks for your great work, can you give me some advice on how to replace your model with my own model to train and test on these data sets?for example semantic3d dataset．

**Comment by LeanderWayne** [comment]
there is instructions in README.md about custom datasets, sementic3d.md about sementic3d dataset. As for sementic3d, the author has already test it, and there is more details in the essay.

**Comment by loicland** [comment]
Semantic3d is already implemented. For your own data there might be a little bit of work, but I give pointers at the end of the main README as well as a template `custom_dataset.py` wrapper inn `/learning/`.
