### ISSUE TITLE
What are the FLOPs of your segmentation model in the semantic segmentation task on the s3dis dataset?

### ISSUE THREAD

**Issue by longmalongma** [loicland/superpoint_graph#221]
What are the FLOPs of your segmentation model in the semantic segmentation task on the s3dis dataset?

**Comment by loicland** [comment]
Do you mean the partition part of the semantic segmentation part? Eitherway, the answer depends on the input cloud...

**Comment by longmalongma** [comment]
Yes, your method has a low argument count, but what about computational complexity? Can the specific FLOPs be given in Partition Part of the Semantic segmentation Part on S3DIS so as to facilitate the comparison experiment?

**Comment by loicland** [comment]
Hi!

We are releasing a new version of SuperPoint Graph called SuperPoint Transformer (SPT).

https://github.com/drprojects/superpoint_transformer

It is better in any way:

| ✨ SPT in numbers ✨ |
| :---: |
| 📊 **SOTA results:** 76.0 mIoU S3DIS 6-Fold, 63.5 mIoU on KITTI-360 Val, 79.6 mIoU on DALES  |
| 🦋 **212k parameters only!** | 
| ⚡ Trains on S3DIS in **3h on 1 GPU**| 
| ⚡ **Preprocessing is x7 faster than SPG!** |
| 🚀  **Easy install** (no more boost!)|

If you are interested in lightweight, high-performance 3D deep learning, you should check it out. In the meantime, we will finally retire SPG and stop maintaining this repo.
