### ISSUE TITLE
make[2]: *** No rule to make target '/lib/libpython3.6m.so', needed by 'libply_c.so'.  Stop.

### ISSUE THREAD

**Issue by kcabhishek** [loicland/superpoint_graph#222]
I keep getting this error while trying to make.

![errorsu](https://user-images.githubusercontent.com/31674144/92038157-93b0a400-ed38-11ea-85f2-4ca014a38fa4.PNG)

Here is my cmake.

![cmake](https://user-images.githubusercontent.com/31674144/92038581-408b2100-ed39-11ea-9c40-38cf71a6c3c9.PNG)
 
Please help!

**Comment by loicland** [comment]
Is your python version 3.6m? Run python to find out.

**Comment by kcabhishek** [comment]
Hello @loicland. Thank you for relying so fast. My python is 3.8 and I fixed the issue by changing it in the command line.  My question is I am trying to do segmentation on a .ply file, will I be able to do that with this? If so, how?

**Comment by loicland** [comment]
Could you post the question in a separate issue? And do you mean partitioning or semantic segmentation?
