### ISSUE TITLE
Some problem in write_semantic3d.py

### ISSUE THREAD

**Issue by zcy1065670505** [loicland/superpoint_graph#228]
Hi,
     Yesterday I have trained two models(for test_full set and test_reduced set).  Successfully in writing test_reduced set labels files(just submitted it to semantic3d.net several minutes ago) and Visualizing the results(including pred/feature/spg .etc).But when I tried to write the labels of test_full set ,Some error ouccred. Commands are as follows:
python partition/write_Semantic3d.py --SEMA3D_PATH $SEMA3D_DIR --odir "results/sema3d/best" --db_test_name test_full 
(Of course there is a file named ‘predictions_test.h5'  in  direction "results/sema3d/best" )

=================
   test_full/
=================
1 / 15---> birdfountain_station1
    reading the subsampled file...
    upsampling...
Traceback (most recent call last):
  File "partition/write_Semantic3d.py", line 73, in <module>
    labels_full = reduced_labels2full(labels_red, components, n_ver)
  File "/media/swjtu-rs/工作/ZCY/superpoint_graph-ssp-spg/partition/provider.py", line 621, in reduced_labels2full
    labels_full[components[i_com]] = labels_red[i_com]
IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed

I don' know what is the mean of the variable 'components', Could you tell me what is the problem?
Thank you !

**Comment by loicland** [comment]
Hi,

sorry I missed your issue.

`components[i_com]` is the content of the superpoints `i_com`, ie the list of indices of the points it contains.

Could you print the shapeand first 10 elements of `labels_red[i_com]` and `components[i_com]`?

**Comment by loicland** [comment]
Hi!

We are releasing a new version of SuperPoint Graph called SuperPoint Transformer (SPT).
It is better in any way:

| ✨ SPT in numbers ✨ |
| :---: |
| 📊 **SOTA results:** 76.0 mIoU S3DIS 6-Fold, 63.5 mIoU on KITTI-360 Val, 79.6 mIoU on DALES  |
| 🦋 **212k parameters only!** | 
| ⚡ Trains on S3DIS in **3h on 1 GPU**| 
| ⚡ **Preprocessing is x7 faster than SPG!** |
| 🚀  **Easy install** (no more boost!)|

If you are interested in lightweight, high-performance 3D deep learning, you should check it out. In the meantime, we will finally retire SPG and stop maintaining this repo.
