### ISSUE TITLE
a lot of problems when compiling cmake 

### ISSUE THREAD

**Issue by Fanyan-0411** [loicland/superpoint_graph#229]
I really appreciate for your kind response first of all!!
I got some problems when doing CMAKE, here are some details of my issue. 
After doing cmake
 
![图片](https://user-images.githubusercontent.com/71177938/99965581-fe212f80-2dcf-11eb-95a4-72e20ce5fd08.png)

Got 
![图片](https://user-images.githubusercontent.com/71177938/99965589-01b4b680-2dd0-11eb-9ceb-0b6ba808a742.png)

It looks no bug in there, but when doing “make”, I got:
 
![图片](https://user-images.githubusercontent.com/71177938/99965600-06796a80-2dd0-11eb-947e-275d824c12e9.png)

And I am sure boost and eigen3 are all well installed, please look:
 
![图片](https://user-images.githubusercontent.com/71177938/99965610-0c6f4b80-2dd0-11eb-8a05-eb7774bf4269.png)

The versions of cmake(3.10), boost(1.67 or 1.65), eigen3(3.3.7) and numpy(1.19) are all appropriate. Please tell me why it still can’t work, and I have tried this for a whole week. Thank you sooooooo much!!!

**Comment by loicland** [comment]
Hi,

the CMAKE output indicates that like your boost libraries are not linking properly.

> Boost LIBRARIES ARE

Try 

`sudo apt-get install  libboost-all-dev`

And when running make add `VERSBOSE=1` the error is a bit generic here

**Comment by Fanyan-0411** [comment]
Thanks for your replay~~~
I have fixed this issue, and the main reason could be dependency problem. The solution of the issue is shown as follows. Hoping it can give some clue to others. 
Firstly, please be sure all the packages are installed correctly. 
![image](https://user-images.githubusercontent.com/71177938/100227407-0f974280-2f5c-11eb-8700-775ee530c179.png)
and then, execute command as usual

> CONDAENV=YOUR_CONDA_ENVIRONMENT_LOCATION 

> cd partition/ply_c

> cmake . -DPYTHON_LIBRARY=$CONDAENV/lib/libpython3.6m.so -DPYTHON_INCLUDE_DIR=$CONDAENV/include/python3.6m -DBOOST_INCLUDEDIR=$CONDAENV/include -DEIGEN3_INCLUDE_DIR=$CONDAENV/include/eigen3

![image](https://user-images.githubusercontent.com/71177938/100228025-08bcff80-2f5d-11eb-8d28-4bb24ad22f05.png)

in this part if you get 

> Boost LIBRARIES ARE
rather than
> Boost LIBRARIES ARE: /home/fanyan2/anaconda3/envs/pytorch3.7/lib

which means cmake didn't find **Boost LIBRARIES**. 

However **libboost-all-dev** was also installed, then you can try to SET the **Boost LIBRARIES DIR** in CMakeLists.txt in the front of command **INCLUDE_DIRECTORIES(${Boost_INCLUDE_DIRS})**, for instance
![image](https://user-images.githubusercontent.com/71177938/100228749-1f178b00-2f5e-11eb-9bdb-f5eaf87233fa.png)

then i get 
![image](https://user-images.githubusercontent.com/71177938/100230287-7f0f3100-2f60-11eb-8786-a451e5c62232.png)

execute make, 
![image](https://user-images.githubusercontent.com/71177938/100230399-a8c85800-2f60-11eb-93fc-cd6d6ed07d1f.png)

emmmmmm, a lot of warnings, but ignore it.

now enjoy coding time~~
