### ISSUE TITLE
ValueError: could not convert string to float: '-9.1\x160'

### ISSUE THREAD

**Issue by whuhxb** [loicland/superpoint_graph#230]
When I running the code:
python partition/partition.py --dataset s3dis --ROOT_PATH $S3DIR_DIR --voxel_width 0.03 --reg_strength 0.03
I encounter this bug on hallway2 of Area3:
xyz = np.ascontiguousarray(room_ver[:, 0:3], dtype='float32')
lib/python3.6/site-packages/numpy/core/_asarray.py", line 177, in ascontiguousarray
    return array(a, dtype, copy=False, order='C', ndmin=1)
ValueError: could not convert string to float: '-9.1\x160'

Has anyone encountered the same problem?

**Comment by loicland** [comment]
Hi,

there are errors in the S3DIS dataset. We provide a patch to remove some of these errors, see:  
`https://github.com/loicland/superpoint_graph/blob/ssp%2Bspg/S3DIS.md`

Let me know if the problem persists.

**Comment by loicland** [comment]
Hi!

We are releasing a new version of SuperPoint Graph called SuperPoint Transformer (SPT).
It is better in any way:

| ✨ SPT in numbers ✨ |
| :---: |
| 📊 **SOTA results:** 76.0 mIoU S3DIS 6-Fold, 63.5 mIoU on KITTI-360 Val, 79.6 mIoU on DALES  |
| 🦋 **212k parameters only!** | 
| ⚡ Trains on S3DIS in **3h on 1 GPU**| 
| ⚡ **Preprocessing is x7 faster than SPG!** |
| 🚀  **Easy install** (no more boost!)|

If you are interested in lightweight, high-performance 3D deep learning, you should check it out. In the meantime, we will finally retire SPG and stop maintaining this repo.
