### ISSUE TITLE
Some Problem About Partition.py

### ISSUE THREAD

**Issue by zcy1065670505** [loicland/superpoint_graph#233]
when I test my custom dataset by runing:（before running,I have modified all the settings related to custom data):
`python partition/partition.py --dataset custom_dataset --ROOT_PATH ./ --voxel_width 0.05 --reg_strength 0.8 --ver_batch 5000000`
some problem happened as follow picture shows:could you tell me what's the matter? thank you for you kind help!
![issue](https://user-images.githubusercontent.com/65106878/102599635-b5536100-4158-11eb-800e-dc12221bd96c.png)

**Comment by loicland** [comment]
Hi,

this is clearly an issue with Qhull and the triangulation, and not cut pursuit. See [here](http://www.qhull.org/html/qh-impre.htm) for more info.

My guess would be that your coordinates are in absolute values and large. Try centering them: 
```
xyz=xyz-xyz.mean(1)
```
where you load the data ([here](https://github.com/loicland/superpoint_graph/blob/497c52e5a6b6253673c4e8585369a46522325b91/partition/partition.py#L136) normally)
