### ISSUE TITLE
How can I predict my ".LAZ" data?

### ISSUE THREAD

**Issue by ZouhairBALLOUCH** [loicland/superpoint_graph#236]
Good evening, please I need your help.
I would like to know after the model training, how I can do for prediction with my point clouds having a ".LAZ" format.
Thank you in advance

**Comment by loicland** [comment]
you can read your point cloud into python with the laspy library. Uncomment the importation of the library in `provider.py` and use our function `read_las`.

**Comment by ZouhairBALLOUCH** [comment]
thank you very much professor

**Comment by loicland** [comment]
Hi!

We are releasing a new version of SuperPoint Graph called SuperPoint Transformer (SPT).
It is better in any way:

| ✨ SPT in numbers ✨ |
| :---: |
| 📊 **SOTA results:** 76.0 mIoU S3DIS 6-Fold, 63.5 mIoU on KITTI-360 Val, 79.6 mIoU on DALES  |
| 🦋 **212k parameters only!** | 
| ⚡ Trains on S3DIS in **3h on 1 GPU**| 
| ⚡ **Preprocessing is x7 faster than SPG!** |
| 🚀  **Easy install** (no more boost!)|

If you are interested in lightweight, high-performance 3D deep learning, you should check it out. In the meantime, we will finally retire SPG and stop maintaining this repo.
