### ISSUE TITLE
Can you share the ScanNet code?

### ISSUE THREAD

**Issue by minkyujeon** [loicland/superpoint_graph#238]
Hello, I highly appreciate you for sharing the code.

I wonder if you can upload the code about 'ScanNet' dataset.

Thank you :)

**Comment by loicland** [comment]
Hi,

I haven't got the chance to adapt the code to scannet yet sorry.

**Comment by loicland** [comment]
Hi!

We are releasing a new version of SuperPoint Graph called SuperPoint Transformer (SPT).
It is better in any way:

| ✨ SPT in numbers ✨ |
| :---: |
| 📊 **SOTA results:** 76.0 mIoU S3DIS 6-Fold, 63.5 mIoU on KITTI-360 Val, 79.6 mIoU on DALES  |
| 🦋 **212k parameters only!** | 
| ⚡ Trains on S3DIS in **3h on 1 GPU**| 
| ⚡ **Preprocessing is x7 faster than SPG!** |
| 🚀  **Easy install** (no more boost!)|

If you are interested in lightweight, high-performance 3D deep learning, you should check it out. In the meantime, we will finally retire SPG and stop maintaining this repo.
