### ISSUE TITLE
Compile the libply_c and libcp libraries 

### ISSUE THREAD

**Issue by ZouhairBALLOUCH** [loicland/superpoint_graph#239]
Hello Sir, 
Can you help me please I always receive errors( errors in the paths) in this part although I replaced $CONDAENV by the path of my environment (C:\ProgramData\Anaconda3 ) and also I do not have the same files for example at the level of Lib I do not have any file which is called libpython3.6.so 
I am working with python 3.8
Thank you in advance

**Comment by loicland** [comment]
Have you tried replacing mentions of python3.6 by python3.8 in the command lines?

**Comment by ZouhairBALLOUCH** [comment]
Yes Professor I replaced 3.6 with 3.8 but in Lib I don't have any file called libpython3.8.so

**Comment by loicland** [comment]
If you have installed conda correctly there must be a `libpython*.so` file in CONDAENV/lib. On a UNIX terminal type:

`libpy="lib/libpython*.so"`
`locate $CONDAENV$libpy

**Comment by ZouhairBALLOUCH** [comment]
I don't use Unix. I have installed Anaconda (Python 3.8) on Windows 10. However I don't find the files you said.
Thank you

**Comment by loicland** [comment]
I don't use windows, so I am not sure how to compile the librairies, but I know it is possible. Have you installed `python3-dev`? Anyway, first step for you would be to locate or install `libpython*.so`.

**Comment by ZouhairBALLOUCH** [comment]
thank you very much professor

**Comment by loicland** [comment]
Hi!

We are releasing a new version of SuperPoint Graph called SuperPoint Transformer (SPT).
It is better in any way:

| ✨ SPT in numbers ✨ |
| :---: |
| 📊 **SOTA results:** 76.0 mIoU S3DIS 6-Fold, 63.5 mIoU on KITTI-360 Val, 79.6 mIoU on DALES  |
| 🦋 **212k parameters only!** | 
| ⚡ Trains on S3DIS in **3h on 1 GPU**| 
| ⚡ **Preprocessing is x7 faster than SPG!** |
| 🚀  **Easy install** (no more boost!)|

If you are interested in lightweight, high-performance 3D deep learning, you should check it out. In the meantime, we will finally retire SPG and stop maintaining this repo.
