### ISSUE TITLE
Has method been applied to 3D Shapes?

### ISSUE THREAD

**Issue by rkjones4** [loicland/superpoint_graph#244]
Hi, 

Very cool project! This is a bit of a general question, but I was wondering if this method has ever been applied to datasets of 3D Shapes instead of Scenes? If not, any insight into how well the method might extend into this domain would be appreciated - thanks!

**Comment by loicland** [comment]
SPG is an algorithm for scaling up semantic  segmentation to large scenes without losing the global structure. For shapes, I feel that the size of point clouds is usually too small to justify using SPG, you are probably better off using KPConv, MinkoNet, or RandLaNet (check out torch-points3d for numerous ready-to-use SOTA implementations).

Unless you have large point clouds, and the shapes' global structure is somehow important to understand their parts?
