### ISSUE TITLE
Using RGB values for custom dataset SPG partition

### ISSUE THREAD

**Issue by sandeepnmenon** [loicland/superpoint_graph#251]
As per the readme: https://github.com/loicland/superpoint_graph#datasets-without-rgb

> If your data does not have RGB values you can easily use SPG. You will need to follow the instructions in partition/partition.ply regarding the pruning.

My data has good calibration and I would like to see the results with rgb values.
Can I use the  prune function as used for s3dis for my dataset to include rgb values
https://github.com/loicland/superpoint_graph/blob/8428739bbbdc9f4843a7114cf757112e1c8fd028/partition/partition.py#L124

Then stack rgb values with `geof`
 `              features = np.hstack((geof, rgb/255.)).astype('float32')#add rgb as a feature for partitioning
`

I am not getting good results with these. Are there any additional changes?

**Comment by loicland** [comment]
Hi!

We are releasing a new version of SuperPoint Graph called SuperPoint Transformer (SPT).
It is better in any way:

| ✨ SPT in numbers ✨ |
| :---: |
| 📊 **SOTA results:** 76.0 mIoU S3DIS 6-Fold, 63.5 mIoU on KITTI-360 Val, 79.6 mIoU on DALES  |
| 🦋 **212k parameters only!** | 
| ⚡ Trains on S3DIS in **3h on 1 GPU**| 
| ⚡ **Preprocessing is x7 faster than SPG!** |
| 🚀  **Easy install** (no more boost!)|

If you are interested in lightweight, high-performance 3D deep learning, you should check it out. In the meantime, we will finally retire SPG and stop maintaining this repo.
