### ISSUE TITLE
ValueError: RANSAC could not find a valid consensus set.

### ISSUE THREAD

**Issue by Xiaofei-Kevin-Yang** [loicland/superpoint_graph#254]
Hi,

Thanks for your excellent work on point cloud segmentation. I encountered an issue when running the ssp-spg in my own dataset as below:  ValueError: RANSAC could not find a valid consensus set.
Traceback (most recent call last):
  File "supervized_partition/graph_processing.py", line 563, in <module>
    main()
  File "supervized_partition/graph_processing.py", line 184, in main
    reg = RANSACRegressor(random_state=0).fit(xyz[low_points,:2], xyz[low_points,2])
  File "/root/miniconda3/lib/python3.7/site-packages/sklearn/linear_model/_ransac.py", line 440, in fit
    "RANSAC could not find a valid consensus set. All"
ValueError: RANSAC could not find a valid consensus set. All `max_trials` iterations were skipped because each randomly chosen sub-sample failed the passing criteria. See estimator attributes for diagnostics (n_skips*).

Could you tell me how to fix it? I really appreciate your help.

**Comment by loicland** [comment]
Hi!

We are releasing a new version of SuperPoint Graph called SuperPoint Transformer (SPT).
It is better in any way:

| ✨ SPT in numbers ✨ |
| :---: |
| 📊 **SOTA results:** 76.0 mIoU S3DIS 6-Fold, 63.5 mIoU on KITTI-360 Val, 79.6 mIoU on DALES  |
| 🦋 **212k parameters only!** | 
| ⚡ Trains on S3DIS in **3h on 1 GPU**| 
| ⚡ **Preprocessing is x7 faster than SPG!** |
| 🚀  **Easy install** (no more boost!)|

If you are interested in lightweight, high-performance 3D deep learning, you should check it out. In the meantime, we will finally retire SPG and stop maintaining this repo.
