### ISSUE TITLE
Question on custom dataset

### ISSUE THREAD

**Issue by Devoe-97** [loicland/superpoint_graph#256]
I run partition.py to prune my point cloud(63825 points, xmin=-0.78, xmax=-0.0367, ymin=-0.1375, ymax=0.08109, zmin=-0.552, zmax=0.568) and i set voxel_width=0.01
and it shows:

`Voxelization into 0 x 0 x 0 grid`
`Reduced from 63825 to 1 points (0%)`

How should i fix thie?
Thanks

**Comment by Devoe-97** [comment]
i use this code `xyz, rgb, labels, o = libply_c.prune(xyz, args.voxel_width, rgb, np.array(1,dtype='uint8'), np.zeros(1, dtype='uint8'), 0, 0)`

**Comment by qzq-hit** [comment]
> I run partition.py to prune my point cloud(63825 points, xmin=-0.78, xmax=-0.0367, ymin=-0.1375, ymax=0.08109, zmin=-0.552, zmax=0.568) and i set voxel_width=0.01
> and it shows:
> 
> `Voxelization into 0 x 0 x 0 grid`
> `Reduced from 63825 to 1 points (0%)`
> 
> How should i fix thie?
> Thanks
Have you solved this problem? It happened when I was pruning my own data set

**Comment by antoine-lag** [comment]
I had the same problem and it came from line 192 of ply_c.cpp, the type of xyz was not float but double

**Comment by loicland** [comment]
Hi!

We are releasing a new version of SuperPoint Graph called SuperPoint Transformer (SPT).
It is better in any way:

| ✨ SPT in numbers ✨ |
| :---: |
| 📊 **SOTA results:** 76.0 mIoU S3DIS 6-Fold, 63.5 mIoU on KITTI-360 Val, 79.6 mIoU on DALES  |
| 🦋 **212k parameters only!** | 
| ⚡ Trains on S3DIS in **3h on 1 GPU**| 
| ⚡ **Preprocessing is x7 faster than SPG!** |
| 🚀  **Easy install** (no more boost!)|

If you are interested in lightweight, high-performance 3D deep learning, you should check it out. In the meantime, we will finally retire SPG and stop maintaining this repo.
