### ISSUE TITLE
The influence of pruning

### ISSUE THREAD

**Issue by baixiao930** [loicland/superpoint_graph#257]
Thanks for your excellent work. 
I am confused about the influence of the pruning operation. The evaluation of partition (BR and BP metric) is based on the pruned points, which means a direct comparison between with no pruning and pruning with some voxel width is not fair. Is that true? If yes, how much influence does `without pruning' have on the partition results?

**Comment by loicland** [comment]
Hi!

We are releasing a new version of SuperPoint Graph called SuperPoint Transformer (SPT).
It is better in any way:

| ✨ SPT in numbers ✨ |
| :---: |
| 📊 **SOTA results:** 76.0 mIoU S3DIS 6-Fold, 63.5 mIoU on KITTI-360 Val, 79.6 mIoU on DALES  |
| 🦋 **212k parameters only!** | 
| ⚡ Trains on S3DIS in **3h on 1 GPU**| 
| ⚡ **Preprocessing is x7 faster than SPG!** |
| 🚀  **Easy install** (no more boost!)|

If you are interested in lightweight, high-performance 3D deep learning, you should check it out. In the meantime, we will finally retire SPG and stop maintaining this repo.
