### ISSUE TITLE
cmake error  

### ISSUE THREAD

**Issue by ZouhairBALLOUCH** [loicland/superpoint_graph#258]
Hi Sir; 
Can you help me to solve this problem 
Thank you very much in advance
![error (1)](https://user-images.githubusercontent.com/62794017/129421831-87975663-1037-4c2a-ba32-14ec48b9999d.JPG)

**Comment by loicland** [comment]
Hi!

We are releasing a new version of SuperPoint Graph called SuperPoint Transformer (SPT).
It is better in any way:

| ✨ SPT in numbers ✨ |
| :---: |
| 📊 **SOTA results:** 76.0 mIoU S3DIS 6-Fold, 63.5 mIoU on KITTI-360 Val, 79.6 mIoU on DALES  |
| 🦋 **212k parameters only!** | 
| ⚡ Trains on S3DIS in **3h on 1 GPU**| 
| ⚡ **Preprocessing is x7 faster than SPG!** |
| 🚀  **Easy install** (no more boost!)|

If you are interested in lightweight, high-performance 3D deep learning, you should check it out. In the meantime, we will finally retire SPG and stop maintaining this repo.
