### ISSUE TITLE
Import libply_c error  

### ISSUE THREAD

**Issue by ayoubOUSSM2021** [loicland/superpoint_graph#259]
Hi Professor; 
Could you help me to solve this problem? 
Best regards  
![errorland](https://user-images.githubusercontent.com/87376316/130283343-d341b44c-873a-4a17-88c6-2da1561bc895.JPG)

**Comment by ayoubOUSSM2021** [comment]
I have solved the problem by python 3.8 , thank you very much

**Comment by loicland** [comment]
Hi!

We are releasing a new version of SuperPoint Graph called SuperPoint Transformer (SPT).
It is better in any way:

| ✨ SPT in numbers ✨ |
| :---: |
| 📊 **SOTA results:** 76.0 mIoU S3DIS 6-Fold, 63.5 mIoU on KITTI-360 Val, 79.6 mIoU on DALES  |
| 🦋 **212k parameters only!** | 
| ⚡ Trains on S3DIS in **3h on 1 GPU**| 
| ⚡ **Preprocessing is x7 faster than SPG!** |
| 🚀  **Easy install** (no more boost!)|

If you are interested in lightweight, high-performance 3D deep learning, you should check it out. In the meantime, we will finally retire SPG and stop maintaining this repo.
