### ISSUE TITLE
The introduction of the ruturn of libcp.cutpursuit

### ISSUE THREAD

**Issue by shaofeifei11** [loicland/superpoint_graph#260]
I am sorry, I can not understand what is the "components", "in_component" (lines 177 of partition/partition.py )

`components, in_component = libcp.cutpursuit(features, graph_nn["source"], graph_nn["target"]
                                         , graph_nn["edge_weight"], args.reg_strength)`

In particular, "in" in "in_component" is an abbreviation of "index"? 

Could you briefly introduce what data is stored in "component" and "In_component"? 

I am very expected to get your help.  Thank you!

**Comment by xfeng853** [comment]
hello, i have the same question,  do you understand them now?

**Comment by azsxdcfvg** [comment]
I think that in_component is the number of components which this point is belonging to.

**Comment by cama36** [comment]
hello, i have the same question, do you understand them now?

**Comment by loicland** [comment]
Hi, sorry for delayed answer.

`components` is a list of size the number of components. `components[c]` is the list of the indices of the vertices in component c.

`in_component` is an array of size n_vertex. `in_component[v]` returns the index of the component containing v.

In other words, `in_component[components[c]]==c`

**Comment by loicland** [comment]
Hi!

We are releasing a new version of SuperPoint Graph called SuperPoint Transformer (SPT).
It is better in any way:

| ✨ SPT in numbers ✨ |
| :---: |
| 📊 **SOTA results:** 76.0 mIoU S3DIS 6-Fold, 63.5 mIoU on KITTI-360 Val, 79.6 mIoU on DALES  |
| 🦋 **212k parameters only!** | 
| ⚡ Trains on S3DIS in **3h on 1 GPU**| 
| ⚡ **Preprocessing is x7 faster than SPG!** |
| 🚀  **Easy install** (no more boost!)|

If you are interested in lightweight, high-performance 3D deep learning, you should check it out. In the meantime, we will finally retire SPG and stop maintaining this repo.
