### ISSUE TITLE
Question about superpoint features and superedge features

### ISSUE THREAD

**Issue by MenglinQiu** [loicland/superpoint_graph#263]
I see that the feature of the superpoint is calculated by the eigen value e of the covariance matrix in graph.py. However, only length e[0], surface e[0]*e[1] and volume e[0]*e[1]*e[2] are used.  Why not generate more different features through the eigen value? such as linearity sphericity planarity and curvature.
These superpoint features seem to be concatenated to the superedge features after parsing, rather than fed into the CRF-ECC together with the superpoint features learned by pointnet.
Could you tell me the reason? Thanks!!

**Comment by loicland** [comment]
Hi, sorry for delayed response.

We assessed experimentally that our edge feature were enough. But no reason not to add those features as well if you think they can help with your application!

**Comment by loicland** [comment]
Hi!

We are releasing a new version of SuperPoint Graph called SuperPoint Transformer (SPT).
It is better in any way:

| ✨ SPT in numbers ✨ |
| :---: |
| 📊 **SOTA results:** 76.0 mIoU S3DIS 6-Fold, 63.5 mIoU on KITTI-360 Val, 79.6 mIoU on DALES  |
| 🦋 **212k parameters only!** | 
| ⚡ Trains on S3DIS in **3h on 1 GPU**| 
| ⚡ **Preprocessing is x7 faster than SPG!** |
| 🚀  **Easy install** (no more boost!)|

If you are interested in lightweight, high-performance 3D deep learning, you should check it out. In the meantime, we will finally retire SPG and stop maintaining this repo.
