### ISSUE TITLE
why superedge features are so important

### ISSUE THREAD

**Issue by azsxdcfvg** [loicland/superpoint_graph#264]
I find that the ECC plays an important role in this network, it usea an MLP to generate filters from superedge feature. so how do you think about this process? why the length ratio, surface ratio, point count ratio are so important and can improve miou by 20 percent, and what it represents in a super point .thank you very much.

**Comment by loicland** [comment]
Hi,

Each superpoint has by definition a simple shape, so classifying them independently is not enough to reach a good performance. Why is why it is important to use the GNN to leverage contextual information.

However the relationship between superpoints is richer than between just points. The size and shape of two adjacent superpoints, as well as the nature of their interface plays a crucial role.

Picture a superpoint corresponding to the wheel of a car. The message will differ depending if they are sent upward to the body of the car, downward to the road, and to a small and distance floating artefact.

I hope that helps, let me know if you have further questions.
