### ISSUE TITLE
ifrozen importlib._bootstrap  in _find_and_load_unlocked ModuleNotFoundError: No module named 'libcp

### ISSUE THREAD

**Issue by WanpengShao** [loicland/superpoint_graph#267]
Hi:

I have this in partition:
sys.path.append("./partition/cut-pursuit/build/src")
sys.path.append("./partition/ply_c")
sys.path.append("./partition")
And I have compliled the libply_c and libcp and get libply_c.so and libcp.so
But still:
Traceback (most recent call last):
File "", line 971, in _find_and_load
File "", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'libcp'
How to fixed it?

**Comment by WanpengShao** [comment]
> 
I have fixed. The reason is even I have
sys.path.append("./partition/cut-pursuit/build/src")
sys.path.append("./partition/ply_c")
sys.path.append("./partition")
But I do not know hwy these scripts does not work. So I just move move libcp.so  libply_c.so from sub-folders to the same folder with the partition. Then the partition code worked.

**Comment by loicland** [comment]
Hi!

We are releasing a new version of SuperPoint Graph called SuperPoint Transformer (SPT).
It is better in any way:

| ✨ SPT in numbers ✨ |
| :---: |
| 📊 **SOTA results:** 76.0 mIoU S3DIS 6-Fold, 63.5 mIoU on KITTI-360 Val, 79.6 mIoU on DALES  |
| 🦋 **212k parameters only!** | 
| ⚡ Trains on S3DIS in **3h on 1 GPU**| 
| ⚡ **Preprocessing is x7 faster than SPG!** |
| 🚀  **Easy install** (no more boost!)|

If you are interested in lightweight, high-performance 3D deep learning, you should check it out. In the meantime, we will finally retire SPG and stop maintaining this repo.
