### ISSUE TITLE
how to generate the trainset'superpoint-graph after oversegment?

### ISSUE THREAD

**Issue by azsxdcfvg** [loicland/superpoint_graph#269]
hellow,In SSP method, i know that we can get a result by using cutpursuit to oversegment eval-set's embedding vector.but how to generate the embedding vector of training-set?just use the same network to generate? Looking forward to your replies,thank you very much

**Comment by loicland** [comment]
Hi!

We are releasing a new version of SuperPoint Graph called SuperPoint Transformer (SPT).
It is better in any way:

| ✨ SPT in numbers ✨ |
| :---: |
| 📊 **SOTA results:** 76.0 mIoU S3DIS 6-Fold, 63.5 mIoU on KITTI-360 Val, 79.6 mIoU on DALES  |
| 🦋 **212k parameters only!** | 
| ⚡ Trains on S3DIS in **3h on 1 GPU**| 
| ⚡ **Preprocessing is x7 faster than SPG!** |
| 🚀  **Easy install** (no more boost!)|

If you are interested in lightweight, high-performance 3D deep learning, you should check it out. In the meantime, we will finally retire SPG and stop maintaining this repo.
