### ISSUE TITLE
TypeError in 'NearestNeighbors(1, algorithm='kd_tree').fit(xyz)'

### ISSUE THREAD

**Issue by Pixie8888** [loicland/superpoint_graph#272]
Dear authors,

When I running 'python partition/partition.py', an error occurred here in the partition/provider.py: 
![image](https://user-images.githubusercontent.com/72333326/185021406-0d3d8c5b-18ac-40e2-a9f8-a60648940b88.png)

What is the value '1' mean in the NearestNeighbors()?

**Comment by loicland** [comment]
It depends on your version of sklearn. Replace with:

`nn=NearestNeighbors(n_neighbors=1,algorithm='kd_tree').fit(xyz)`

**Comment by Pixie412** [comment]
Hi,
Thanks for the reply. I encountered another problem when computing area3 hallway_2: 
![image](https://user-images.githubusercontent.com/72333326/187012287-622d8a02-95cf-4e85-a97f-3ab9fcad7343.png)
I didn't modify the the original s3dis data. Neither do I found any strange character in the hallway_2 file. How to solve this error？

**Comment by Pixie8888** [comment]
Thanks
