### ISSUE TITLE
CUDA error when training for Semantic3D

### ISSUE THREAD

**Issue by MEnesAtik** [loicland/superpoint_graph#274]
Hello,

Thank you for the codes. When I train for Semantic3D I get the following error in the epoch that should save the checkpoint. Do you have a solution suggestion?
Thank you for your answer.

![error](https://user-images.githubusercontent.com/55531103/193022463-5835d094-48de-46c7-88c2-187b9dfbc629.PNG)

**Comment by loicland** [comment]
Hi!

We are releasing a new version of SuperPoint Graph called SuperPoint Transformer (SPT).
It is better in any way:

| ✨ SPT in numbers ✨ |
| :---: |
| 📊 **SOTA results:** 76.0 mIoU S3DIS 6-Fold, 63.5 mIoU on KITTI-360 Val, 79.6 mIoU on DALES  |
| 🦋 **212k parameters only!** | 
| ⚡ Trains on S3DIS in **3h on 1 GPU**| 
| ⚡ **Preprocessing is x7 faster than SPG!** |
| 🚀  **Easy install** (no more boost!)|

If you are interested in lightweight, high-performance 3D deep learning, you should check it out. In the meantime, we will finally retire SPG and stop maintaining this repo.
