### ISSUE TITLE
the version of metrics

### ISSUE THREAD

**Issue by ziwenjie** [loicland/superpoint_graph#275]
Hi:
Which version of metrics do you use?
I have tried all version of metrics, but these have no ConfusionMatrix. like following
```
AttributeError: module 'metrics' has no attribute 'ConfusionMatrix'
```
Best 
ziwenjie

**Comment by loicland** [comment]
Try `confusion_matrix` ?

**Comment by ziwenjie** [comment]
> Try `confusion_matrix` ?
Thanks for your reply.
I'm sorry for that, I made a mistake. The metrics toolkit is written by you.
Best
ziwenjie
