### ISSUE TITLE
CMake error

### ISSUE THREAD

**Issue by ardianumam** [loicland/superpoint_graph#280]
Hi,

Thanks for the great work! I try to run the cmake script and got this error:
```
CMake Error: The current CMakeCache.txt directory /home/aumam/dev/SPNet/lib/ply_c/CMakeCache.txt is different than the directory /test/work2020/superpoints/spnet/lib/ply_c where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt
```
Any direction?

Thanks

**Comment by loicland** [comment]
Hi!

We are releasing a new version of SuperPoint Graph called SuperPoint Transformer (SPT).

https://github.com/drprojects/superpoint_transformer

It is better in any way:

| ✨ SPT in numbers ✨ |
| :---: |
| 📊 **SOTA results:** 76.0 mIoU S3DIS 6-Fold, 63.5 mIoU on KITTI-360 Val, 79.6 mIoU on DALES  |
| 🦋 **212k parameters only!** | 
| ⚡ Trains on S3DIS in **3h on 1 GPU**| 
| ⚡ **Preprocessing is x7 faster than SPG!** |
| 🚀  **Easy install** (no more boost!)|

If you are interested in lightweight, high-performance 3D deep learning, you should check it out. In the meantime, we will finally retire SPG and stop maintaining this repo.
