### ISSUE TITLE
ModuleNotFoundError: No module named 'torchnet'

### ISSUE THREAD

**Issue by whuhxb** [loicland/superpoint_graph#282]
Hi @loicland , 

I have run the learning code of SPG on S3DIS dataset, and I have installed torchnet with pip install torchnet or pip install git+https://github.com/pytorch/tnt.git@master , but when running this code, the error occurs that no module named 'torchnet'. Have you ever met this error? How to solve? Thanks a lot.

File "./learning/s3dis_dataset.py", line 15, in <module>
    import torchnet as tnt
ModuleNotFoundError: No module named 'torchnet'

**Comment by loicland** [comment]
have you tried installing torchnet?

**Comment by whuhxb** [comment]
> have you tried installing torchnet?

Yes. I have installed torchnet. Pytorch version is 0.4.0. I have no idea why this bug occur. Have you ever met this bug?

**Comment by loicland** [comment]
Hi!

We are releasing a new version of SuperPoint Graph called SuperPoint Transformer (SPT).

https://github.com/drprojects/superpoint_transformer

It is better in any way:

| ✨ SPT in numbers ✨ |
| :---: |
| 📊 **SOTA results:** 76.0 mIoU S3DIS 6-Fold, 63.5 mIoU on KITTI-360 Val, 79.6 mIoU on DALES  |
| 🦋 **212k parameters only!** | 
| ⚡ Trains on S3DIS in **3h on 1 GPU**| 
| ⚡ **Preprocessing is x7 faster than SPG!** |
| 🚀  **Easy install** (no more boost!)|

If you are interested in lightweight, high-performance 3D deep learning, you should check it out. In the meantime, we will finally retire SPG and stop maintaining this repo.
