### ISSUE TITLE
L0-cut pursuit partition algorithm

### ISSUE THREAD

**Issue by jing-zhao9** [loicland/superpoint_graph#284]
Hello Professor！
Which function does libcp. cutpursuit() specifically refer to?
![image](https://user-images.githubusercontent.com/104781102/226857263-e4acc0f5-5e94-4039-84dd-1d69623fabe8.png)

**Comment by loicland** [comment]
https://github.com/loicland/cut-pursuit

**Comment by jing-zhao9** [comment]
> https://github.com/loicland/cut-pursuit

Professor, thank you for your answer. Do you have Python source code for cut-pursuit

**Comment by loicland** [comment]
Hi!

We are releasing a new version of SuperPoint Graph called SuperPoint Transformer (SPT).

https://github.com/drprojects/superpoint_transformer

It is better in any way:

| ✨ SPT in numbers ✨ |
| :---: |
| 📊 **SOTA results:** 76.0 mIoU S3DIS 6-Fold, 63.5 mIoU on KITTI-360 Val, 79.6 mIoU on DALES  |
| 🦋 **212k parameters only!** | 
| ⚡ Trains on S3DIS in **3h on 1 GPU**| 
| ⚡ **Preprocessing is x7 faster than SPG!** |
| 🚀  **Easy install** (no more boost!)|

If you are interested in lightweight, high-performance 3D deep learning, you should check it out. In the meantime, we will finally retire SPG and stop maintaining this repo.
