### ISSUE TITLE
About the number of superpoints

### ISSUE THREAD

**Issue by jing-zhao9** [loicland/superpoint_graph#286]
Hello professor！
Is it possible to achieve the number of points in a fixed superpoint and the number of fixed superpoints？

**Comment by loicland** [comment]
you can control the size of superpoint with --reg_strength and the minimal size of superpoints with --cutoff, but you can't control the exact number of sp or their exact size.

**Comment by loicland** [comment]
Hi!

We are releasing a new version of SuperPoint Graph called SuperPoint Transformer (SPT).

https://github.com/drprojects/superpoint_transformer

It is better in any way:

| ✨ SPT in numbers ✨ |
| :---: |
| 📊 **SOTA results:** 76.0 mIoU S3DIS 6-Fold, 63.5 mIoU on KITTI-360 Val, 79.6 mIoU on DALES  |
| 🦋 **212k parameters only!** | 
| ⚡ Trains on S3DIS in **3h on 1 GPU**| 
| ⚡ **Preprocessing is x7 faster than SPG!** |
| 🚀  **Easy install** (no more boost!)|

If you are interested in lightweight, high-performance 3D deep learning, you should check it out. In the meantime, we will finally retire SPG and stop maintaining this repo.
