### ISSUE TITLE
How to set the parameters in Geometric Partition of SPG?

### ISSUE THREAD

**Issue by ErrorMakerqwq** [loicland/superpoint_graph#294]
Hi,Loic

The parameters and effect I set of the Geometric Partition part are shown in the attachment. You can see that the TV on the wall is not distinguished, and there are many similar situations, such as doors and Windows(Fig.1,Fig.2).

1. Is it possible to set parameters to separate objects that are close together, like the image in your paper (Fig.3)?
2. How do I set these parameters if I can, such as: k_nn_geof, k_nn_adj (Your repo address: https://github.com/loicland/superpoint_graph/blob/ssp%2Bspg/partition/partition.py).
<img width="547" alt="1" src="https://github.com/loicland/superpoint_graph/assets/90616786/aa3e24df-18b6-4b7d-aa9e-4bb07ff7e293">
<img width="832" alt="2" src="https://github.com/loicland/superpoint_graph/assets/90616786/1ad808f4-d5f6-4f4d-8290-a522dbba82e9">
<img width="470" alt="3" src="https://github.com/loicland/superpoint_graph/assets/90616786/4f9ee36a-f9f3-4e44-8064-ec357a39b244">

**Comment by ErrorMakerqwq** [comment]
I made a mistake in the color of the point cloud input and the issue has been fixed.

**Comment by loicland** [comment]
glad to hear it!
