### ISSUE TITLE
Loading of trained network

### ISSUE THREAD

**Issue by JD-ETH** [loicland/superpoint_graph#3]
I am trying to load the trained network as in instruction, but can't seem to unzip the tar file from the link. 

I was running following command:

`tar -xvzf  model_sema3d_trainval.pth.tar
`
And receive the following error message:

> gzip: stdin: not in gzip format
> tar: Child returned status 1
> tar: Error is not recoverable: exiting now

Any idea why this is happening?

**Comment by mys007** [comment]
Hi, it is indeed slightly confusing but in PyTorch, `pth.tar` is the whole file extension and it is not supposed to be decompressed manually. It is to be loaded directly by `--resume some_dir/model_sema3d_trainval.pth.tar`.

**Comment by JD-ETH** [comment]
@mys007  Thanks for the comment. I am not familiar with pytorch :P 
This issue can be closed now. I found another small issue that the cloud_precomputation needs to be manually done before running the saved model:

`python learning/sema3d_dataset.py --SEMA3D_PATH=$SEMA3D_DIR`

Otherwise the parsed/ folder still shows empty.

**Comment by mys007** [comment]
Yes, we mention this point in the README in the Training section, but it is indeed necessary for testing as well, thanks.
