### ISSUE TITLE
Semantic 3D for Training, Test reduced set custom

### ISSUE THREAD

**Issue by amandaloh16** [loicland/superpoint_graph#30]
Hello,
I am trying to test some data I have, it is in x,y,z,i,i,i,i format to try and match the other reduced set .txts with x,y,z,i,r,g,b since I have no training data with labels so I must use Semantic3D for training. 

Can I just train with the Semantic 3D data but test with custom .txts in Semantic3D format. I am unclear still from the documentation how I can achieve this? Do I have to retrain all over again to just test my data?

**Comment by loicland** [comment]
Hi,

You dont need to put empty values for i r g b if you do not have them. Simply write your loading function to output xyz (I already wrote the functions for .ply and .las format). Then follow the instructions in ```partition/partition.py``` for `custom_dataset`, I wrote examples of pruning without rgb nor labels.

You will need to retrain the models on semantic from scratch without rgb values (see [issue #6](https://github.com/loicland/superpoint_graph/issues/6) for the command lines).

Then adapt the beginning of ```learning/semantic3d_dataset``` to add a new test set.

Let me know if you encounter a problem!

Loic

**Comment by amandaloh16** [comment]
So I wrote a custom format which is basically the same as semantic3D format minus anything rgb related, but I am confused because in training it's looking for a parsed folder but that's not produced in the partition step. Am I missing something?

**Comment by amandaloh16** [comment]
So some follow up questions:
1. If I am to use same exact format as semantic3d but just add a new test file to the reduced set, how do I modify semantic3d_dataset.py? (My test file is .txt in same exact format of reduced set for Semantic3D). Do I have to just add the name of my new test files to the valid_names and everything else stays the same, or is there more to modify?

2. I made a brand new custom dataset method in provider.py, which is just a copy of the semantic3d set but just witholding rgb as you said, and filled out partition.py to call it and run the partition line: 

`python partition/partition.py --dataset custom_dataset --ROOT_PATH /home/amanda/Semantic3D --voxel_width 0.05 --reg_strength 0.8 --ver_batch 5000000`

However, this command is taking way longer than expected and when I have run it in the past: like >2hrs: is this normal?

EDIT:
for:
`python learning/sema3d_dataset.py --SEMA3D_PATH /home/amanda/Semantic3D
`
to run I have to change preprocess_pointclouds method in sem3d_dataset.py:

                xyz = f['xyz'][:]
                # rgb = f['rgb'][:].astype(np.float)
                elpsv = np.stack([ f['xyz'][:,2][:], f['linearity'][:], f['planarity'][:], f['scattering'][:], f['verticality'][:] ], 
                axis=1)
               # rescale to [-0.5,0.5]; keep xyz
                elpsv[:,0] /= 100 # (rough guess)
                elpsv[:,1:] -= 0.5
                #rgb = rgb/255.0 - 0.5
                P = np.concatenate([xyz, elpsv], axis=1)

but now running:

`CUDA_VISIBLE_DEVICES=0 python learning/main.py --dataset sema3d --SEMA3D_PATH /home/amanda/Semantic3D \
--db_train_name trainval --epochs 500 --lr_steps '[350, 400, 450]' --test_nth_epoch 100 \
--model_config 'gru_10,f_8' --ptn_nfeat_stn 8 --pc_attribs "xyzelpsv" --nworkers 2 \
 --odir "results/sema3d/sema_3d_model"`

I get this error: 
  File "/home/amanda/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py", line 54, in conv1d
    return f(input, weight, bias)
RuntimeError: Given groups=1, weight[64, 8, 1], so expected input[752, 5, 128] to have 8 channels, but got 5 channels instead

am I not making the right changes in sem3d_dataset.py?

**Comment by loicland** [comment]
Hi, sorry for the delayed answer, I hope it is still relevant to you!

1- create a folder 'my_test_set' in `/data`, put your files here. Add `my_test_set` to the data sets line 40 of `/partition/partition.py`,  and add the following line35 of `learning/sema3d_dataset.py`:

```
elif args.db_test_name == 'my_test_set':
testset = ['my_test_set'/' + os.path.splitext(f)[0] for f in os.listdir(args.SEMA3D_PATH + '/superpoint_graphs/my_test_set')]
```

2 - no it's not normal, it should take minutes, unless: your data set is huge (how many points?), or you are running out of RAM. Monitor your RAM, and if critical descrease `--ver_batch` to 1000000

3 - I do not have an explanation on the top of my head. It seems like your superpoints only load 5 attributes. can you run the code in debug mode, and check what is loaded in `learning/spg.py` line 212?

**Comment by amandaloh16** [comment]
What I'm trying to clarify which is the source of the dimension issue is: in sem3d_dataset.py:

the line:  P = np.concatenate([xyz, elpsv], axis=1)
am I supposed to omit the rgb value? My rgb is now an empty list when we make the changes you said to specify above: I think the line is originally:
line 95:  P = np.concatenate([xyz, rgb, elpsv], axis=1)

This one line code change is what is causing the dimension issues throughout the rest of the code.

**Comment by loicland** [comment]
You are right, it is the incriminating line. You can either:
- fill the rgb values with zeros (inefficient but easy)
- change line 212 in `learning/spg.py` to reflect that the columns are different:
```
if 'xyz' in args.pc_attribs: columns.append(P[:,:3])
if 'e' in args.pc_attribs: columns.append(P[:,3,None])
if 'lpsv' in args.pc_attribs: columns.append(P[:,4:7])
```

**Comment by amandaloh16** [comment]
Yes! I found the line, thanks resolved.
