### ISSUE TITLE
Windows Support?

### ISSUE THREAD

**Issue by DrFridolin** [loicland/superpoint_graph#35]
Hello and thank you for making this code available.

Is it possible to use this code on a Windows machine or is it for Linux only?

Thanks.

**Comment by loicland** [comment]
Hi,

As of now, the code is not tested with PyTorch0.4, which is the first one with windows compatibility I think. Once we have made the necessary changes, the code should be able to run on windows (although I can't try it out myself). The only tricky part would be compiling the .so, but should be doable with gnuwin32.

Will contact you when the port to 0.4 is done (soon!).

loic

**Comment by DrFridolin** [comment]
loic, many thanks for your reply. I am looking forward to windows support, in the meantime, I'll work on getting it running on an Ubuntu machine.
