### ISSUE TITLE
Question about the label

### ISSUE THREAD

**Issue by Nicny** [loicland/superpoint_graph#45]
Hello,
I am trying to train a model on my own dataset. The label in my dataset are 0 and 1. When I create feature.h5 and super_point_graph.h5, It become all-zeros. I am sure of the label while reading correct. It seems that something wrong in "libply_c.prune" because the input label of this function is correct but the output(labels_sub) maybe wrong(col 1 all one, col 2 & 3 all zero)

**Comment by loicland** [comment]
Hi,

the label '0' is reserved for unlabelled points. Also what is the spatial extent of your data?
