### ISSUE TITLE
 File "/home/administrator/anaconda3/lib/python3.6/site-packages/tqdm/_tqdm.py", line 931, in __iter__ for obj in iterable:

### ISSUE THREAD

**Issue by chowkamlee81** [loicland/superpoint_graph#49]
I want to train on semantic3d dataset. I followed the procedure to partition first and then train
After executing train "CUDA_VISIBLE_DEVICES=0 python learning/main.py --dataset sema3d --SEMA3D_PATH /home/administrator/Documents.orig/Kumar_FileSystem/Server_Code/sematic3d --db_test_name testred --db_train_name trainval --epochs 500 --test_nth_epoch 100 --model_config 'gru_10,f_8' --ptn_nfeat_stn 11 --nworkers 2 --odir "/home/administrator/Documents.orig/Kumar_FileSystem/results/sema3d/trainval_best""

it started throwing an error below: Kindly help

Epoch 0/500 (/home/administrator/Documents.orig/Kumar_FileSystem/results/sema3d/trainval_best):
  0%|                                                                         | 0/7 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/usr/share/pycharm/helpers/pydev/pydevd.py", line 1599, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/usr/share/pycharm/helpers/pydev/pydevd.py", line 1026, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/usr/share/pycharm/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/administrator/Documents.orig/Kumar_FileSystem/Server_Code/sematic3d/superpoint_graph-release/learning/main.py", line 387, in <module>
    main()
  File "/home/administrator/Documents.orig/Kumar_FileSystem/Server_Code/sematic3d/superpoint_graph-release/learning/main.py", line 286, in main
    acc, loss, oacc, avg_iou = train()
  File "/home/administrator/Documents.orig/Kumar_FileSystem/Server_Code/sematic3d/superpoint_graph-release/learning/main.py", line 169, in train
    for bidx, (targets, GIs, clouds_data) in enumerate(loader):
  File "/home/administrator/anaconda3/lib/python3.6/site-packages/tqdm/_tqdm.py", line 931, in __iter__
    for obj in iterable:
  File "/home/administrator/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 336, in __next__
    return self._process_next_batch(batch)
  File "/home/administrator/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
KeyError: 'Traceback (most recent call last):\n  File "/home/administrator/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop\n    samples = collate_fn([dataset[i] for i in batch_indices])\n  File "/home/administrator/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in <listcomp>\n    samples = collate_fn([dataset[i] for i in batch_indices])\n  File "/home/administrator/anaconda3/lib/python3.6/site-packages/torchnet/dataset/listdataset.py", line 54, in __getitem__\n    return self.load(self.list[idx])\n  File "/home/administrator/Documents.orig/Kumar_FileSystem/Server_Code/sematic3d/superpoint_graph-release/learning/spg.py", line 148, in loader\n    cloud, diam = load_superpoint(args, db_path + \'/superpoint_graphs/\' + fname + \'.h5\', G.vs[s][\'v\'], train, test_seed_offset)\n  File "/home/administrator/Documents.orig/Kumar_FileSystem/Server_Code/sematic3d/superpoint_graph-release/learning/spg.py", line 189, in load_superpoint\n    P = hf[\'{:d}\'.format(id)]\n  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper\n  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper\n  File "/home/administrator/anaconda3/lib/python3.6/site-packages/h5py/_hl/group.py", line 167, in __getitem__\n    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)\n  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper\n  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper\n  File "h5py/h5o.pyx", line 190, in h5py.h5o.open\nKeyError: "Unable to open object (object \'2324\' doesn\'t exist)"\n'

Process finished with exit code 1

**Comment by loicland** [comment]
Hi,

Did you pre-process the data after the partition (which would have created the folder `/parsed`)?

Else you should run the code in debug mode, put a stopping point line 189 of `/partition/spg` and check wether the corresponding superpoint graph folder  indeed exists. If so open the h5 file and check wether or not in contains a superpoint with index 2324.

Let me know how this goes.

**Comment by chowkamlee81** [comment]
Thanks... Got the issue. I missed pre-process the data after the partition (which would have created the folder /parsed. Hence closing the issue
