### ISSUE TITLE
Why is the cut-pursuit folder empty?

### ISSUE THREAD

**Issue by dleam** [loicland/superpoint_graph#5]
My friend, I want to compile libcp libraries, but there seems to be nothing in the cut-pursuit folder. Did I just miss something?

**Comment by loicland** [comment]
Hi,

It seems like there is a problem with the cut pursuit submodule. In the meantime, you can clone [this repo](https://github.com/loicland/cut-pursuit) in the ```/partition/``` folder manually.

**Comment by dleam** [comment]
Thx, my friend! It works.
