### ISSUE TITLE
Inference issue:partition/visualize.py", prediction_testred.h5 not created line 64, in <module>     raise ValueError("%s does not exist and is needed to output the result ply" % res_file

### ISSUE THREAD

**Issue by chowkamlee81** [loicland/superpoint_graph#52]
Used pytorch3.1
a) did partition
b) reorganize point clouds into superpoints 
c) tested the pretrained model  on the full test using
CUDA_VISIBLE_DEVICES=0,1 python learning/main.py --dataset sema3d --SEMA3D_PATH /home/administrator/Documents.orig/Kumar_FileSystem/Server_Code/sematic3d --db_test_name testfull --db_train_name trainval --epochs -1 --test_nth_epoch 100 --model_config 'gru_10,f_8' --ptn_nfeat_stn 11 --nworkers 2 --odir "results/sema3d/trainval_best" --resume RESUME
d) python partition/visualize.py --dataset sema3d --ROOT_PATH /home/administrator/Documents.orig/Kumar_FileSystem/Server_Code/sematic3d --res_file '/home/administrator/Documents.orig/Kumar_FileSystem/results/sema3d/trainval_best/prediction_testred' --file_path 'test_reduced/MarketplaceFeldkirch_Station4' --output_type ifprs

Kindly suggest:

Now getting error below:

Traceback (most recent call last):
  File "partition/visualize.py", line 64, in <module>
    raise ValueError("%s does not exist and is needed to output the result ply" % res_file) 
ValueError: /home/administrator/Documents.orig/Kumar_FileSystem/results/sema3d/trainval_best/prediction_testred.h5 does not exist and is needed to output the result ply

**Comment by loicland** [comment]
duplicate [with this issue](https://github.com/loicland/superpoint_graph/issues/53)
