### ISSUE TITLE
the semantic3D  trained network model cannot download

### ISSUE THREAD

**Issue by renhaofan** [loicland/superpoint_graph#55]
the link you give is:
http://imagine.enpc.fr/%7Esimonovm/largescale/model_sema3d_trainval.pth.tar
when I open it, it's:

Not Found
The requested URL /~simonovm/largescale/model_sema3d_trainval.pth.tar was not found on this server.
Apache Server at certis.enpc.fr Port 80

**Comment by renhaofan** [comment]
I added the same issue in the download link of S3DIS trained network model

**Comment by loicland** [comment]
Hi,

this is weird, I'm contacting martin now. In the meantime, send me an email at loic.landrieu@ign.fr with the network you want I will send it to you.

**Comment by mys007** [comment]
The server is back up, it was a temporary outage. Thanks for making us aware!
