### ISSUE TITLE
out of memory or no space left on device

### ISSUE THREAD

**Issue by renhaofan** [loicland/superpoint_graph#56]
From some issues, I know your GPU is 1080Ti  having about 11G memory.  my GPU is TITAN-X having about 12G memory. So when I want to  `train on the whole publicly available data and test on the reduced test set`, I run  "CUDA_VISIBLE_DEVICES=0 python learning/main.py --dataset sema3d --SEMA3D_PATH $SEMA3D_DIR --db_test_name testred --db_train_name trainval \
--epochs 500 --lr_steps '[350, 400, 450]' --test_nth_epoch 100 --model_config 'gru_10,f_8' --ptn_nfeat_stn 11 \
--nworkers 2 --odir "results/sema3d/trainval_best",.
there is a oserror about `out of memory`， I'm so wired. how is possible?, I just easily retried the command above. It's solved.

but when I want to ` test this network on the full test set, ` I run "CUDA_VISIBLE_DEVICES=0 python learning/main.py --dataset sema3d --SEMA3D_PATH $SEMA3D_DIR --db_test_name testfull --db_train_name trainval \
--epochs -1 --lr_steps '[350, 400, 450]' --test_nth_epoch 100 --model_config 'gru_10,f_8' --ptn_nfeat_stn 11 \
--nworkers 2 --odir "results/sema3d/trainval_best" --resume RESUME
"
an error occurs:
```
/home/renhaofan/superpoint_graph/learning/metrics.py:66: RuntimeWarning: invalid value encountered in true_divide
  return sum(values) / class_seen�����������                         | 8/15 [00:29<00:25,  3.66s/it]
-> Multisample 10: Test accuracy: 100.0, �Test oAcc: 0.0,  Test avgIoU: nan, 00:Test mAcc: 0.03s/it]
Traceback (most recent call last):����������                         | 8/15 [00:28<00:25,  3.61s/it]
  File "learning/main.py", line 387, in <module>                     | 8/15 [00:28<00:25,  3.61s/it]
    main()����������������������������������                         | 8/15 [00:28<00:25,  3.60s/it]
  File "learning/main.py", line 315, in main                         | 8/15 [00:28<00:25,  3.58s/it]
    hf.create_dataset(name=fname, data=o_cpu) #(0-based classes)     | 8/15 [00:28<00:24,  3.55s/it]
  File "/home/renhaofan/anaconda3/lib/python3.6/site-packages/h5py/_hl/group.py", line 106, in create_dataset
    dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)   | 8/15 [00:28<00:24,  3.55s/it]
  File "/home/renhaofan/anaconda3/lib/python3.6/site-packages/h5py/_hl/dataset.py", line 143, in make_new_dset
    dset_id.write(h5s.ALL, h5s.ALL, data)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 221, in h5py.h5d.DatasetID.write
  File "h5py/_proxy.pyx", line 132, in h5py._proxy.dset_rw
  File "h5py/_proxy.pyx", line 93, in h5py._proxy.H5PY_H5Dwrite
OSError: Can't prepare for writing data (file write failed: time = Fri Aug 31 10:22:30 2018
, filename = 'results/sema3d/trainval_best/predictions_testfull.h5', file descriptor = 5, errno = 28, 
error message = 'No space left on device', buf = 0x5645813f8510, total write size = 51592, 
bytes this sub-write = 51592, bytes actually written = 18446744073709551615, offset = 483328)
```
I noticed the error message `No space left on device`, when I just retried the command again and at the same time, I run `nvidia-smi -l` to check the situation of GPU memory Usage, I noticed  that when my memory usage reached the 9947 MiB,  the program print the same message below unchanged for several minutes:
![image](https://user-images.githubusercontent.com/25266337/44891045-c372de80-ad0f-11e8-8dbc-3f92ff381ae3.png)
and it finally print:
![bugs3](https://user-images.githubusercontent.com/25266337/44891092-059c2000-ad10-11e8-826a-10fa340dcf29.png)
I noticed that a `key number 8`, I thinks maybe it's about that. 
And in my directory 
![bugs33](https://user-images.githubusercontent.com/25266337/44891188-8ce99380-ad10-11e8-9626-8d10fad674bb.png)
so I think everything is ok, but I just so wired why I just easily the command, the issues can be solved. 
Record here for discussion

**Comment by loicland** [comment]
`No space left on device` means your disk is full.
