### ISSUE TITLE
Is that possible to run partition process on GPU?

### ISSUE THREAD

**Issue by Jinkelee** [loicland/superpoint_graph#57]
Hi, thanks a lot for your great work. I want to ask , is that possible to run partition.py on a GPU. Cause the partition process spends a lot of time.

**Comment by loicland** [comment]
Hi,

it is not possible to run the partition on GPU for now. However, we are adressing this issues and will release a series of updates in the upcoming months:

- L0-cut pursuit will soon be multithreaded, which will cut the computation time by almost an order of magnitude
- we will release a new supervized partition step, which is not only more precise but also much faster.

I will update this issue when it is done.

Note that if speed is really an issue for you, you can increase the initial subsampling, at the cost of a small dip in precision.

**Comment by Jinkelee** [comment]
I'm so glad to hear that and looking forward to the improvement! 
And thanks for the advice, I will try it and try my best to make some speedup in the code.
