### ISSUE TITLE
Any possibility to train network of semantic 3D on multi-gpu?

### ISSUE THREAD

**Issue by staochun** [loicland/superpoint_graph#58]
I have tried to train s3d network on a single GPU according to your instruction. However, there is usually an out-of-memory error on CUDA during the training epochs so that the training cannot experience enough epochs. So I would like to ask for some improvement advice for upgrading to multi-GPU version. I have tried several ways but no one succeeds. Thanks for your kind help very much.

**Comment by loicland** [comment]
Hi,

I don't really know anyhting about multiple GPU setup, but I am surprised that you are running out of memory. We were able to train the model on a GPU with only 6BG of memory thanks to the momory monger.

Are you using the recommended reg_strength?
What is your setup?
Have you tries increasing the voxel width to decrease the cloud size?

**Comment by staochun** [comment]
Hi. I have used the recommended reg_strength. And my setup is:
CUDA_VISIBLE_DEVICES=4 python learning/main.py --dataset sema3d --SEMA3D_PATH /data/staochun/superpoint_graph-release/dataset_s3d --db_test_name testred --db_train_name trainval \
--epochs 98 --lr_steps '[350, 400, 450]' --test_nth_epoch 33 --model_config 'gru_10,f_8' --ptn_nfeat_stn 6 \
--nworkers 5 --odir "results/s3d/trainval_best"

I have already reduced my training epoch in a case out of memory error. But I would like to ask what is the momory monger you mentioned in your answer.  We are quite interested in it. Thank you!

**Comment by ShengyuH** [comment]
hi, sure you can do it. just compose ptn and ecc into one model and wrap this model with nn.DataParallel()
