### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by nicolas-chaulet** [loicland/superpoint_graph#59]
Hi Loic! 
I just installed superpoint and I ran into some small installation issues, mainly related to installing cut-pursuit, I thought I would share them here:

1. `libboost_python.so` and  `libboost_numpy.so` were missing from the conda install of boost, I had  `libboost_python36.so` and  `libboost_numpy36.so` instead. This caused the cmake command to break. The fix consists in creating  `libboost_python.so` and  `libboost_numpy.so` as symbolic link to the  `libboost_python36.so` and  `libboost_numpy36.so`files

2. I had to edit the `CMakeLists.txt` according to https://github.com/loicland/superpoint_graph/issues/36#issue-329197836 for the compilation to run

3. I see that you have changed the README regarding building cut-pursuit from
    ```
    cd cut-pursuit/src
    ```
    to 
    ```
    cd cut-pursuit
    ```
    I just cloned cut-pursuit and the CMakefileList.txt is in the `cut-pursuit/src` folder, therefore the previous REDAME was correct. Am I missing something?

**Comment by loicland** [comment]
Hi,

1 and 2 : thank you for pointing this out to me. We are working on a new parallellized version of L0-cut pursuit to eb released soon, and we will make sure that those installation problems are solved then. In the meantime, thanks for pointing out your solutions. I will make sure to refer to it if omeone else get stuck.

3 - this one was a mistake on my part, now fixed.

**Comment by nicolas-chaulet** [comment]
Hi, no worries! And thanks for making this available.
