### ISSUE TITLE
ply_c make error

### ISSUE THREAD

**Issue by ytgcljj** [loicland/superpoint_graph#60]
autoware16@autoware16:~/superpoint_graph/partition/ply_c$ make
CMakeFiles/ply_c.dir/build.make:95: *** target pattern contains no '%'。 停止。
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/ply_c.dir/all' failed
make[1]: *** [CMakeFiles/ply_c.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Kienlgk** [comment]
I solved this by  checking path of $CONDAENV in build.make file and correct it by
```
$ export CONDAENV='/home/<user>/anaconda3/envs/<your_conda_env>'
```
