### ISSUE TITLE
What is the geometric feature multiply by 2? 

### ISSUE THREAD

**Issue by amandaloh16** [loicland/superpoint_graph#64]
Hello, 

I had a question for this line in partition.py:

            elif args.dataset=='sema3d':
                 features = geof
                 geof[:,3] = 2. * geof[:, 3]

Why do you multiply the verticality feature by 2?

**Comment by loicland** [comment]
Hi,

So just to be clear, the partition step is unsupervized with handcrafted features for now. I will release a trainable partition step in the next few weeks, with greatly improved results.

Basically you can use whatever combination of features you feel will work for your dataset. In my experiments the 4th columns (verticality) was very discriminative to distinguish between walls and ground, so I increased its influence for both s3dis and sema3d.

You can try other combination, or wait for the next version which earns those points embeddings from the data itself.
