### ISSUE TITLE
Bug in spg_reader.py?  number of class related.

### ISSUE THREAD

**Issue by leemengwei** [loicland/superpoint_graph#65]
In spg.py def spg_reader, there's might a wrongly fixed paramter '8' in line 73 specifying numbers of class when no labels are avaliable:
The code is：
def spg_reader(args, fname, incl_dir_in_name=False):
    """ Loads a supergraph from H5 file. """
    f = h5py.File(fname,'r')
    if f['sp_labels'].size > 0:
        node_gt_size = f['sp_labels'][:].astype(np.int64) # column 0: no of unlabeled points, column 1+: no of labeled points per class
        node_gt = np.argmax(node_gt_size[:,1:], 1)[:,None]
        node_gt[node_gt_size[:,1:].sum(1)==0,:] = -100    # superpoints without labels are to be ignored in loss computation
    **_else:
        N = f['sp_point_count'].shape[0]
        node_gt_size = np.concatenate([f['sp_point_count'][:].astype(np.int64), np.zeros((N,8),_** dtype=np.int64)], 1)
        node_gt = np.zeros((N,1), dtype=np.int64)

I guess "8" should be number_of_class+1(background)?

**Comment by loicland** [comment]
You are correct, thanks for pointing this out. Will change it by next version.

**Comment by cbyzju** [comment]
actually, this "8" should just be number_of_class, rather than number_of_class+1(background), since this "1(background)" have already been concatenated.
