### ISSUE TITLE
Question About Square Root for Linearity, Planarity, and Scattering

### ISSUE THREAD

**Issue by amandaloh16** [loicland/superpoint_graph#67]
Hello,

Wanted some clarification for these lines in the code: in ply_c.cpp

float linearity  = (sqrtf(lambda[0]) - sqrtf(lambda[1])) / sqrtf(lambda[0]);
float planarity  = (sqrtf(lambda[1]) - sqrtf(lambda[2])) / sqrtf(lambda[0]);
float scattering =  sqrtf(lambda[2]) / sqrtf(lambda[0]);

Why do you take the square root of each lambda before computing? In many research papers I noticed eigen values are not square rooted so wondering why you chose to.

**Comment by loicland** [comment]
Hi,

this was based on the original formulation of the dimensionality by  Demantké etal. [3.1](http://recherche.ign.fr/labos/matis/pdf/articles_conf/2011/laserscanning2011_demantke_final.pdf).

I think the rationale is that the eigenvalues have the dimension of a square distance (from the covariance matrix), and the square root make them homogeneous to a distance.

I ill soon be releasing an update to this repo in which these features will be learned through supervision, which gives much better oversegmentation.
