### ISSUE TITLE
Partitioning comes out differently.

### ISSUE THREAD

**Issue by leemengwei** [loicland/superpoint_graph#68]
Hello @loicland , during in my specific use(I want to do segmentation with high precision), I found that partition will somehow give different results over runs on same data, especially when voxel width and reg strength are set to small values like 0.001, this become even more noticeable.
I understand that partition is given by unsupervised clustering algorithms, yet I still want to make them exactly the same over runs. Any suggestion how can I fulfil that?
Thanks!

**Comment by loicland** [comment]
Hi,

the stochasticity comes from the parallelization in cut pursuit. If perfect reproducibility is a major point for you and you are ready to sacrifice some computational speed (up to 50%), then you can deactivate openmp in cut pursuit.

I think the easier way to do that would be to remove the openmp tag in the CMakeList in `cutpursuit/src`. Let me know if it doesn't work!

loic
