### ISSUE TITLE
About the label of the test data in Semantic3d Dataset

### ISSUE THREAD

**Issue by LZDSJTU** [loicland/superpoint_graph#7]
Hello. I have a question about semantic3d dataset. 

I find that the dataset does not provide labels of the test data. I want to ask if we can only upload the label 
that we predict to the website to check the accuracy. Can we get the label of the test data?

Thank you very much!

**Comment by loicland** [comment]
Hi,

no you can never get the labels of the test data, only the accuracy.

**Comment by LZDSJTU** [comment]
Thank you^_^
