### ISSUE TITLE
Question about upsampling 

### ISSUE THREAD

**Issue by staochun** [loicland/superpoint_graph#71]
In order to meet my requirements on some aspects, I have to try to do upsampling on a data file included in S3D dataset with the param '--upsample 1' to get the full visualization result. And I follow your instruction to adjust the param ver_batch to a constant larger than one, which is five, to adapt to a larger dataset.  And as you have written in the readme file, it takes a too long time for me to doubt whether what I have done is right. lol.  And did you try to do some similar things in the S3D dataset by upsampling or just your own prediction that the upsampling procedure maybe takes a long time? (In our custom dataset, which is quite small, although it also takes a long time but it's not too long and we can endure that. But in the tremendously big S3D dataset, I quite doubt my command line.) Until now the process is to be (2170.55 minutes)24 hours to execute. Thanks for your kind help!

**Comment by loicland** [comment]
Hi,

24 hours seems way too much. A few pointers:

- how much RAM do you have?
- ver_batch is the size of the chunks of points read from the data file at once. It should be around a few millions, not 5
- lastly we are going to release a memory efficient, CPU parallelized version of cut pursuit in the coming weeks. It should cut considerably the computation  time.
