### ISSUE TITLE
A new idea about the issue

### ISSUE THREAD

**Issue by luoxiaoliaolan** [loicland/superpoint_graph#72]
@loicland 
I would like to ask if you have recently updated  this issue? I hope to run this program with TensorFlow , cause it have a better visualization module for check the detail of training process.
In the recent experiment, I got a good prediction. Would you like to ask if you have any further improvements to this issue?

**Comment by loicland** [comment]
Hi,

Which issue are you referring to?

**Comment by longmalongma** [comment]
> Hi,
> 
> Which issue are you referring to?

Can you post your tensorflow-based code?If not, is there a good way to convert pytorch's code to tensorflow's code
