### ISSUE TITLE
How long does this network need to train on the semantic3d?

### ISSUE THREAD

**Issue by LZDSJTU** [loicland/superpoint_graph#8]
I train on the semantic3d on my computer and I surprisedly find that the train process is very fast which is nearly 10 minutes(just approximate, but actually it is very fast). I want to ask if it is normal. 

It took a lot of time to preprocess the dataset such as generating the feature. But training is very fast.

**Comment by loicland** [comment]
Hi,

each epoch should take about 30 second (on a 1080Ti), is that what you observed? Semantic should need at least 400 epochs, so it should take at least a couple hours.
