### ISSUE TITLE
files inside 'parsed' and 'clouds' folders

### ISSUE THREAD

**Issue by yaping222** [loicland/superpoint_graph#85]
I'm running codes on my own dataset. It is stored in '.txt' with x,y,z coordinates. I adapted the codes and I got feature files and spg files for my point clouds. During the training process, it requires a file under 'parsed' folder. However, the partition codes didn't generate 'parsed' files for me, even no empty 'pased' folder.
I'm wondering what should be inside the 'parsed' folder and how to get 'parsed' files.

Another question:
The 'clouds' folder is generated automatically but no files inside, only empty folders. What files are expected in 'clouds' folder?

**Comment by loicland** [comment]
Hi,

as stated in the README, the files must be prepared (i.e. stroed contiguously in memory to speed up computations). It should be pretty fast:
```python learning/s3dis_dataset.py --S3DIS_PATH $S3DIR_DIR```

In the folder `clouds` will be stored visualization of the different steps using the `partition/visualize.py` function.

**Comment by yaping222** [comment]
It works now. Thank you very much!
