### ISSUE TITLE
Points cannot be reduced during in the pruning

### ISSUE THREAD

**Issue by yaping222** [loicland/superpoint_graph#86]
Hi Loic,
Thank you very much for your great code and helpful answers.
I found a difficulty in reducing the number of points. The code runs well but it seems the pruning makes no sense. Also, constructing the superpoint graph takes several hours. I wonder whether this is normal or not.
```
    creating the feature file...
=========================
======== pruning ========
=========================
Voxelization into 1506288 x 499968 x 202504 grid
Reduced from 5000000 to 4999826 points (99.99%)
=========================
======== pruning ========
=========================
Voxelization into 2000000 x 1750016 x 215954 grid
Reduced from 5000000 to 4999968 points (99.99%)
=========================
======== pruning ========
=========================
Voxelization into 1693488 x 1250048 x 177684 grid
Reduced from 5000000 to 4999953 points (99.99%)
=========================
======== pruning ========
=========================
Voxelization into 2000000 x 1500032 x 221214 grid
Reduced from 5000000 to 4999958 points (99.99%)
=========================
======== pruning ========
=========================
Voxelization into 2000000 x 249984 x 230716 grid
Reduced from 2301974 to 2301941 points (99.99%)
59% done                                                  
    computing the superpoint graph...
        minimal partition...
L0-CUT PURSUIT WITH L2 FIDELITY
PARAMETERIZATION = FAST
Graph 22301648 vertices and 535239504 edges and observation of dimension 4
Iteration   1 - 7979 components - Saturation   0.0 % - Quadratic Energy 42.961 % - Timer  464.649
Iteration   2 - 11006 components - Saturation  13.4 % - Quadratic Energy 39.053 % - Timer  1066.94
Iteration   3 - 12448 components - Saturation  30.8 % - Quadratic Energy 38.203 % - Timer  1575.69
Iteration   4 - 13032 components - Saturation  84.6 % - Quadratic Energy 38.027 % - Timer  2033.73
Iteration   5 - 13207 components - Saturation  48.0 % - Quadratic Energy 37.970 % - Timer  2474.01
Stopping criterion reached
```
I'm using airborne laser scanning data. The input file is 1000m*1000m with 22301974 points in total. Here is a screenshot of the data. I wonder what are the possible reasons of the failure in pruning.
![image](https://user-images.githubusercontent.com/47004480/52210761-39174380-2888-11e9-9c84-a67102194a6a.png)

Look forward to your reply.

**Comment by loicland** [comment]
Hi,

I have never tried SPG on aerial data, so I have no guarantee that the spatial features are relevant here.

First, the default pruning parameter is 3 or 5 cm depending on your dataset. I don't think it is well adapted here. I would recommend 50 cm or even 1m.

Second, 13.000 superpoints seems way too much as well. I would recommend increasing the regularization strength.

Try this command:

```
python partition/partition.py --dataset s3dis --ROOT_PATH $S3DIR_DIR --voxel_width 1 --reg_strength 0.2
```

ans post an example of partition (option `p` in `visualize.py`)

**Comment by yaping222** [comment]
Hi Loic,
Thank you very much for your suggestions. Did you mean decreasing the regularization strength to 0.2?
I used --voxel_width 1 --reg_strength 0.1.
Here is an example of my segmentation. 
![image](https://user-images.githubusercontent.com/47004480/52412172-4463ac80-2ade-11e9-9d4c-a3b605beeb2f.png)

My current issue is that it always takes very long time for 'computation of the SPG ...'. For some samples, it even stuck at 'computation of the SPG ...',  so I skipped those samples. I wonder whether the long computation is because I have too many segments?

**Comment by loicland** [comment]
This segmentation seems not bad at all! How many superpoints is that? How big is the pruned cloud?

How much RAM do you have? You should monitor your RAM usage and check if the computation of the superpoint saturates it. Usin swap memory would be extremely slow indeed.

**Comment by yaping222** [comment]
Thank you very much for your suggestions :)

**Comment by yaping222** [comment]
Hi Loic, I realize that your algorithm is quite efficient except when constructing the superpoint graph. 
tri = Delaunay(xyz) is slow. Could you suggest any other faster triangulation function?

**Comment by loicland** [comment]
This one seems good: https://github.com/ashwin/gDel3D

If you ever manage to make it work please let me know how much faster it is, and also how memory hungry it is on the GPU and RAM.

Note that it carries a licence.

**Comment by yaping222** [comment]
Hi Loic, thank you very much for your link. I will try it and let you know if I make it.
