### ISSUE TITLE
Issues on the S3DIS Dataset when testing

### ISSUE THREAD

**Issue by Yajha** [loicland/superpoint_graph#90]
Hi.

When i run test code on the S3DIS Dataset (Partition Part is OK) , the program will always stuck on this situtaion(82%), Hou could i fix this?

![2019-03-03_18-58-13](https://user-images.githubusercontent.com/14049009/53694219-98646700-3de6-11e9-80a0-1f138b2add4d.png)

Thank you for your work!

**Comment by loicland** [comment]
Hi,

Does it always crash at the same time? On the 8th run of he inference on the first fold at 82%? What about the other folds?

Does this work with `--test_multisamp_n 1`? If so it should give results almost as good with a ten times faster inference.

Are you monitoring your GPU memory? Could it be that it saturates?

I think this could be related to [https://github.com/loicland/superpoint_graph/issues/81](this issue). Maybe try the "attempt" fix.

Let me know if it doesn't fix it.

**Comment by Yajha** [comment]
Thank you very much, the code works with `--test_multisamp_n 1`

To your question,
Yes, it always gets stuck on the 8th run on the first fold at 82% with no error information.I have check the GPU memory and there is no problem.
But I still don't know why the problem occurs.

Thanks for your time!

**Comment by Yajha** [comment]
Thank you very much.
The code works with --test_multisamp_n 1.But I still don't know why that problem occurs.


Thanks for your time.








| |
袁嘉
|
|
yj_seu2013@163.com
|
签名由网易邮箱大师定制
On 3/4/2019 19:09，Loic Landrieu<notifications@github.com> wrote：

Hi,

Does it always crash at the same time? On the 8th run of he inference on the first fold at 82%? What about the other folds?

Are you monitoring your GPU memory? Could it be that it saturates?

I think this could be related to [https://github.com//issues/81](this issue). Maybe try the "attempt" fix.

Let me know if it doesn't fix it.
