### ISSUE TITLE
Please help me the dataloader in main.py is not an iterator HOW COME ?! 

### ISSUE THREAD

**Issue by moemen95** [loicland/superpoint_graph#92]

**Comment by loicland** [comment]
Can you be more precise? What is the error message, and which step is failing?

**Comment by moemen95** [comment]
Hello Ioicland thanks for your reply

in function train the for loop of dataloader of iterations the code doesn't enter the for loop

as you see this error come because the dataloader didn't even iteratre

![image](https://user-images.githubusercontent.com/10872652/54497901-ee69fc00-4908-11e9-8e15-edc2f127fcaa.png)

**Comment by moemen95** [comment]
Ok i have found my issue the batch size was 2 and i only have one file.
Thank you
