### ISSUE TITLE
confused with label=0 in seamntci3d dataset

### ISSUE THREAD

**Issue by justbin1123** [loicland/superpoint_graph#94]
dear loic:
     Thank you very much for your great work!
     Oringin semantci3d dataset has night labels value:0-9. As far as i know，pointCNN had removed the data which lable=0. I know indirectly that you have done the same.But i didnt find the code which did that thing.
two issues:

1. Where is the code that removes the data(label=0)?

2. My own large scale outdoor point cloud data is the same with the semantic3d. And i want to try your code . My own dataset has 10 class,like that:
others :0
poles: 1
...
ground： 9
I would like to reserve the data which label=0. Under the circumstances that the semantic3d code will remove that data. What should i do for that? Change the code to reserve the data that lable=0 or start label from 1 without 0?

**Comment by loicland** [comment]
see this issues:

https://github.com/loicland/superpoint_graph/issues/83
https://github.com/loicland/superpoint_graph/issues/63
https://github.com/loicland/superpoint_graph/issues/45

let me know if this doesn't clear up your confusion.

**Comment by justbin1123** [comment]
> _No description provided._

**Comment by loicland** [comment]
Hi,

label 0 is reserved in semantic3d for unannotated data, which are excluded from the evaluation metric. We have followed the same standard. Hence 0 should only be reserved for unannotated data. If you don't have any, start the labels at 1.

However, since our newtork associates a label to all (super)points, the output starts at 0, which corresponds to the label 1 in the input. A little bit confusing I know; but it made the evaluation functions much easier for us.

Let me know if this doesn't completely clear things up for you.

**Comment by justbin1123** [comment]
Thanks a lot！
“label 0 is reserved in semantic3d for unannotated data, which are excluded from the evaluation metric. ” Is that mean label 0  isn’t involved in training（/back propagation ）？But in fact, label =0 was sent to the model，how did u do it？  I guess you deleted label=0 during the data preprocessing process，but i didn't find the code.

**Comment by loicland** [comment]
> mean label 0 isn’t involved in training

correct. We are sometimes dealing with point clouds which are sparsely annotated, and don't want unlabelled point to influennce the training phase. Note that this is different from a 'background' class, as the label unnannotated is never assigned by the network.

The label of superpoints is the  majority label of the points it contains. In the event where a superpoint contains no labeled point, it is assigned the label -100.
See line 69 of `training/spg.py` and line 375 of `main.py`.

**Comment by justbin1123** [comment]
get it！ 
Thank u so much！
