### ISSUE TITLE
Wanna ask about can i take the intensity as an input feature and if i can do that how i do it ?!  thank you so much.

### ISSUE THREAD

**Issue by moemen95** [loicland/superpoint_graph#95]

**Comment by loicland** [comment]
of course you can!You will need to:
- write your read_custom_dataset function such that it returns the intensity in `partition/provider`
- adapt the its call in `partition.py` line 136
- adapt write_features and read_features to take and write the intensity
- add the intensity to P at the equivalent of line 94 of `learning/custom_dataset.py` in your own dataset loader
- adapt the loading of point attributes in `/learning/spg.py` line 213
- adapt the value of `--ptn_nfeat_stn` to take the new value into account

A lots of small changes, but most of them is just one line. Let me know if you get stuck.
